### ISSUE TITLE
Regex blacklist not updating

### ISSUE THREAD

**Issue by Kopernikus1979** [jacklul/pihole-updatelists#1]
Hi,

First of all thx for creating this scipt (for Phole 5 beta).
I've installed it and all seems te be working fine except for the regex blacklist.
When the script is running it I get "collected 16 regexps from the mmmotti list" so it's downloading but at the end it shows 0 number of regex blacklist. The gravity domains are updated, for the whitelists I don't now since I already had the anudeep whitelist.

Thx

**Comment by Kopernikus1979** [comment]
Update:

Deleted my whitelist and I have the same problem as with the regex blacklist, the list is downloaded from anudeep but is not updating.

**Comment by jacklul** [comment]
I will look into it when I can.

For now I want you to check if the records are being properly inserted.

While running my script do you see "inserted: " lines with records that doesn't show up?
Is there any error message directly after those lines?

Can you run the script and interrupt(Ctrl-c) just when the gravity update starts (and lists are being downloaded, do not interrupt after last list had been downloaded), open the database file and look around the tables for the records that supposedly were inserted but doesn't show up? Are they there?

Sqlite DB browser will be useful.

Also: Have you tried shutting down pihole-FTL before running my script ?

**Comment by Kopernikus1979** [comment]
Hi,

Test 1:
I did following, updated Pi-hole to latest branch.
Deleted my regex blacklist filter (since I readded them manually)
Update gravity
Run your script
As you can see the regex blacklist filter are not inserted (see atachement)

[Test 1.txt](https://github.com/jacklul/pihole-updatelists/files/4307540/Test.1.txt)

Test 3:
Stopped pihole-FTL service
Run your scipt
Same result

Test 2:
Will do this test this evening (at work now...)

**Comment by jacklul** [comment]
You should be using script from beta branch, master is for Pi-hole v4 only

**Comment by Kopernikus1979** [comment]
I did, using this one:

wget -q -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/beta/install.sh | sudo bash

**Comment by Kopernikus1979** [comment]
Seems somthing was wrong afterall, deleted the old script.
Rerun wget -q -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/beta/install.sh | sudo bash

But now I get: 
Enabling and starting pihole-updatelists.timer...
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is inactief

Any idea how to resolve?

**Comment by jacklul** [comment]
No idea about that systemd error but script should be available at that point

**Comment by Kopernikus1979** [comment]
Got it working :-)

The trick was to iadd init=/bin/systemd to my /boot/cmdline.txt

Thx for you help!

**Comment by Kopernikus1979** [comment]
Forgot.. one more question
To manually run the script I had to type: sudo ./pihole-updatelists (got message that it nooded root rights)
So I was wondering if "ExecStart=/usr/local/sbin/pihole-updatelists" in the service file will need to be changed to "sudo ExecStart=/usr/local/sbin/pihole-updatelists".

**Comment by jacklul** [comment]
Services already are started as root if not specified otherwise.

**Comment by Kopernikus1979** [comment]
Ok, great.
Thx again!
