### ISSUE TITLE
uBlock Origins sync

### ISSUE THREAD

**Issue by Epic-hunt** [jacklul/pihole-updatelists#103]
This is probably not the right place, as the tool does exactly what it should,  keeps pihole in sync all the time.  But I found I need to use uBlock Origin browser extension to block ads on YouTube and similar sites even while running pihole.  You can manually add the same lists in firebog and copy a whitelist in the uBlock settings.   Maybe an enhancement to uBlock or a separate addon that "updates" uBlock Origin browser extension,  just like pihole-updatelists updates pihole.  probably a whole new project from this.

**Comment by jacklul** [comment]
This is out of scope of this project unfortunately.
