### ISSUE TITLE
Disk shortage /var/log/pihole-FTL.log ahead: 99% used

### ISSUE THREAD

**Issue by Stephen988** [jacklul/pihole-updatelists#104]
Hello,
I don't know when this error was started (I'm using watchtower for weekly update), but now I have found my raspberry with full disk!
I have disabled logs, can be release a fix?
and OT question, my roots on raspbian is completely full? I don't know how to clean and where this data is located!

**Comment by jacklul** [comment]
You should direct this issue to [Pi-hole's repository](https://github.com/pi-hole) as this is repository only for pihole-updatelists script.
