### ISSUE TITLE
Fresh PiHole Install + pihole-updatelists

### ISSUE THREAD

**Issue by Vallesuski** [jacklul/pihole-updatelists#107]
Hi, I just installed Pi-Hole in my Raspberry Pi and also added _pihole-updatelists_.
Install finished OK --> https://i.imgur.com/HwacvMA.png

If I go to "Group Management --> Adlists" I just see 1 default list from Pi-Hole --> https://i.imgur.com/dVijK9Y.png

What else I need to do in order to have "pihole-updatelists" working?
New user here =S

**Comment by jacklul** [comment]
Please read the README carefully, you have to configure it after installing then run it to apply the initial configuration

**Comment by Vallesuski** [comment]
Thanks for your reply.

I want to use "firebog" add list -- Based on README I added URL as follows in /etc/pihole-updatelists.conf--> https://i.imgur.com/NRlNLYy.png

That should be good enough to have _pihole-updatelists_ working?
Do I need to run another command to run it?

**Comment by jacklul** [comment]
Run `pihole-updatelists` once or wait for scheduled run

**Comment by Vallesuski** [comment]
It worked perfect. Thank you so much for your help.
