### ISSUE TITLE
wget fails

### ISSUE THREAD

**Issue by stevefxp1** [jacklul/pihole-updatelists#109]
Hello,

I am building a custom pihole image and your wget command is failing at the end. I would add wget to your run command that installs php items, as it looks like wget is not installed natively.

**Comment by jacklul** [comment]
You mean the install command in Dockerfile? I see that wget is in there

**Comment by jacklul** [comment]
I don't understand...
https://github.com/jacklul/pihole-updatelists/blob/master/Dockerfile

**Comment by stevefxp1** [comment]
OK so I decided to use your updated Dockerfile but I have a couple of questions:

1) Why do you have a copy of the install.sh in line 2 when it does not exist yet. Isnt this part of the file when you issue the wget?

**Comment by jacklul** [comment]
Because the Dockerfile in the repository assumes you have the repository cloned in the same directory, it's for automatic building of the image mostly

**Comment by stevefxp1** [comment]
Ahh...ok makes sense. 

You call out the ability to edit your configuration file with nano but it does not seem you include nano in your image. You might want to review that. I took your image and added nano and good to go on editing the configuration file.

**Comment by jacklul** [comment]
Why edit it inside the container when you can edit those through mounted volumes?

**Comment by stevefxp1** [comment]
Hmmm...never really thought about doing it that way.
