### ISSUE TITLE
GROUP_ID=

### ISSUE THREAD

**Issue by p1r473** [jacklul/pihole-updatelists#11]
Hi Jack,
Would it make sense if GROUP_ID= applied to whitelist and blacklist too? 
Or even a separate flag?
Just a thought.

**Comment by jacklul** [comment]
What do you mean? It does apply to whitelist and blacklist entries

**Comment by p1r473** [comment]
So 0 is the default group, but 0 is disabled, so if I add everything to 0 then run my deleted disabled script, everything will be removed right away?

```
#!/bin/bash
#Delete disabled adlists:
sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM adlist WHERE enabled = 0;" 
#Delete disabled whitelist/blacklist domains
sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM domainlist WHERE enabled = 0;"
#Delete duplicates from gravity
sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM gravity WHERE rowid NOT IN (SELECT rowid FROM gravity GROUP BY domain);"
#Vacuum the DB
sudo sqlite3 /etc/pihole/gravity.db "VACUUM;" 
/bin/bash /home/linaro/git.sh
```

**Comment by jacklul** [comment]
> Sorry, I thought in my testing the whitelist/blacklist does not get disabled. Will retest once we fix the other issue.
> 
> So 0 is the default group, but 0 is disabled, so if I add everything to 0 then run my deleted disabled script, everything will be removed right away?
> I am not sure if its a great idea to default add everything disabled- unless I am missing something
> 
> ```
> #!/bin/bash
> #Delete disabled adlists:
> sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM adlist WHERE enabled = 0;" 
> #Delete disabled whitelist/blacklist domains
> sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM domainlist WHERE enabled = 0;"
> #Delete duplicates from gravity
> sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM gravity WHERE rowid NOT IN (SELECT rowid FROM gravity GROUP BY domain);"
> #Vacuum the DB
> sudo sqlite3 /etc/pihole/gravity.db "VACUUM;" 
> /bin/bash /home/linaro/git.sh
> ```

Group ID = 0 is the default group that every entry is added anyway

**Comment by p1r473** [comment]
So should I be adding everything to group 1 so my script doesn't delete it as soon as I'm done adding it?
