### ISSUE TITLE
[Feature request] Assign Group_ID to multiple groups

### ISSUE THREAD

**Issue by dannykorpan** [jacklul/pihole-updatelists#111]
It would be great to assign ADLISTS_URL, WHITELIST_URL, REGEX_WHITELIST_URL, BLACKLIST_URL and REGEX_BLACKLIST_URL to multiple groups.

**Comment by jacklul** [comment]
Pointless since you can have just one group with updated lists and add your clients to that group while also having custom groups

**Comment by dannykorpan** [comment]
O.k. maybe I have a problem in understanding the docs. I set up a remote adblock list URL in pihole-updatelists.conf. How is it possible to assign all lists from the remote adblock URL to e.g. group 1,3 and 5?

**Comment by jacklul** [comment]
You don't, you simple create new group (for example with ID=9) and add that group to your clients in addition to groups 1, 3 and 5.
