### ISSUE TITLE
custom GRAVITY_DB on usb disk error Exception: SQLSTATE[HY000] [14] unable to open database file

### ISSUE THREAD

**Issue by daemon110282** [jacklul/pihole-updatelists#112]
Hi!

Sorry my english.
I am set custom GRAVITY_DB to usb disk "/mnt/mydisc/etc/pihole/gravity.db".
pihole work fine with this path.

And after run "sudo pihole-updatelists" get error "Exception: SQLSTATE[HY000] [14] unable to open database file"

Can you help me?

**Comment by jacklul** [comment]
That's weird, maybe you could make a symlink to `/mnt/mydisc/etc/pihole/gravity.db` and give the script symlink path instead of the original?

**Comment by daemon110282** [comment]
Thanks! Sorry, my error in file path.
