### ISSUE TITLE
Fedora requires additional package 'php-process'

### ISSUE THREAD

**Issue by jnk22** [jacklul/pihole-updatelists#119]
Hi, I have installed your tool on a new Fedora system today.

When running `pihole-updatelists` I got the following error message:

```
Make sure PHP's functions 'posix_getuid' and 'posix_kill' are available!
```

I was able to solve this by installing the package `php-process` with `dnf install php-process`, as those commands seem to be in another package on Fedora (see comment at [PHP: posix_getuid - Manual](https://www.php.net/manual/de/function.posix-getuid.php#126886)).
Everything else seems to work as expected now.

The system OS used is: **Fedora Linux 36 (Server Edition)**

I don't know if this is relevant to you as your readme uses the `apt` command and therefore another OS as me, but just wanted to post this in case you are interested in this solution for other users.

**Comment by jacklul** [comment]
Thanks for the info, that does seem to be the case for non-apt distros I guess
