### ISSUE TITLE
Why do we need to disable default gravity update schedule?

### ISSUE THREAD

**Issue by PythonOrC** [jacklul/pihole-updatelists#122]
title.

In the guide, it says that I should only skip this step if I don't want to keep the list updated or have gravity update be on. What exactly does the gravity update do and why should I disable it? Thanks

**Comment by jacklul** [comment]
It's because my script runs gravity update after doing it's thing (unless it's disabled via config), making Pi-hole's redundant.

**Comment by PythonOrC** [comment]
Ah ok, that makes a lot of sense. Thank you ❤️
