### ISSUE TITLE
Support configuration via environment variables

### ISSUE THREAD

**Issue by andrewfraley** [jacklul/pihole-updatelists#123]
First off, thanks for this, this seems to be the best way to manage external lists in pihole containers.  It would be great if some of the config could be set as environment variables.  The use case is for running in Docker, it would be great not to have to touch anything except set WHITELIST_URL as an environment variable for the container, then updatelists could pick it up from there.  Apologies if this functionality already exists, but I wasn't able to find it.  Thanks!

**Comment by jacklul** [comment]
That's something I won't be able to implement currently - you will have to use config instead.

**Comment by jacklul** [comment]
Found some time to work on this - will be available soon.

**Comment by jacklul** [comment]
Implemented in dev branch and image for now - https://github.com/jacklul/pihole-updatelists/tree/1130290cd37404a7cdf20d937cf4ce210ecd3098

**Comment by andrewfraley** [comment]
This is perfect, thanks!

**Comment by jacklul** [comment]
This should now be in master and latest image
