### ISSUE TITLE
Attaching to running docker container?

### ISSUE THREAD

**Issue by DieSchoeneWolke** [jacklul/pihole-updatelists#124]
Hey and thank you!
Is it possible to attach the script to a running pi hole docker container so I don't have to rebuild?

**Comment by jacklul** [comment]
I don't think you can do this without actually installing the script inside the container. 
I'm not a Docker expert though and I might be wrong.

**Comment by DieSchoeneWolke** [comment]
Thanks that did it!
However I had wasn't able to restart the DNS trough the cli but through the admin panel. 
Could you help me out once more about how I can check if the script is doing it's job?

Have a great weekend and happy holidays soon!

**Comment by jacklul** [comment]
Just remember that scheduled run won't be able to execute the last command so I suggest checking [out this](https://github.com/jacklul/pihole-updatelists#running-custom-commands-beforeafter-scheduled-run).

**Comment by DieSchoeneWolke** [comment]
oof. Sorry for being too lazy but honestly as a relatively new user I can't study every repo, especially since I'm trying to run a pi-hole on my openmediavault server for like 2 months. 😭 
I ran the script at the default values beside the edited gravity.db path from my docker volume. I then edited the /etc/pihole-updatelists.conf and included the recommended firebog and whitelist file. Should this suffice with the last hint you gave me?

**Comment by jacklul** [comment]
No, it won't reload DNS server after weekly scheduled update.
As mentioned in my previous message you have to edit one thing:

```bash
sudo systemctl edit pihole-updatelists.service
```
```
[Service]
Type=oneshot
ExecStartPost=docker exec -it pihole "pihole restartdns"
```
This should do it but I cannot guarantee it.

**Comment by 7efneBepMM2uGhfzmGpK** [comment]
`sudo systemctl edit pihole-updatelists.service` doesn't work because systemctl isn't installed in my container.

**Comment by 7efneBepMM2uGhfzmGpK** [comment]
`sudo systemctl edit pihole-updatelists.service doesn't work because systemctl isn't installed in my container.`

**Comment by DieSchoeneWolke** [comment]
`sudo systemctl edit pihole-updatelists.service` doesn't work because systemctl isn't installed in my container.

**Comment by jacklul** [comment]
You should execute those on the host machine, where you installed my script.

**Comment by DieSchoeneWolke** [comment]
Ah now it broke the ice I hope.
So I started from scratch now with this repo. I think I completely misunderstood the point of this.
So basically what I only needed to do is to run the script on my host, then use your docker image instead of the official one, configure this as explained in the docker section with the additional volume and then just configure the `/etc/pihole-updatelists.conf` file on my host machine, right?

**Comment by jacklul** [comment]
If you want to use the image from this repo you shouldn't install the script in the host machine at all.
The script will run inside the container if you use **jacklul/pihole** image, the steps I wrote earlier are for the cases where you don't want to use anything than official **pihole/pihole** image but still use this script.
