### ISSUE TITLE
Invalid Whitelist

### ISSUE THREAD

**Issue by danezmotion** [jacklul/pihole-updatelists#125]
Hello,
Im getting an error when trying to add the anudeep whitelist.
Im not sure where to debug and I have run out of solves.

--------------------
Fetching WHITELIST from '/etc/pihole/list_white_anudeep.txt'... done (1 entries)
Processing...
Invalid: https://raw.githubusercontent.com/anudeepnd/whitelist/master/domains/whitelist.txt
Summary: 1 invalid
---------------------

Any ideas?

**Comment by jacklul** [comment]
`WHITELIST_URL` must point to list like `https://raw.githubusercontent.com/anudeepnd/whitelist/master/domains/whitelist.txt`, they way you've done it is incorrect.

**Comment by danezmotion** [comment]
oh, ok. Thank you.
That did work. However, I have it like this in the ADLISTS_URL and that worked great.
How come this doesn't work the same?

**Comment by jacklul** [comment]
Because only `ADLISTS_URL` has that specific behavior.
