### ISSUE TITLE
Package php-process required as new dep in Centos Stream 9

### ISSUE THREAD

**Issue by digitalxruin** [jacklul/pihole-updatelists#126]
Fresh install of Centos Stream 9 and Pi-hole.
Made sure I had the php deps listed installed and used your script.
Installed fine but running it failed with the following:

```
# /usr/local/sbin/pihole-updatelists
Make sure PHP's functions 'posix_getuid' and 'posix_kill' are available!
```
After some quick searching I found the following fixed it:
```
# dnf install php-process
# /usr/local/sbin/pihole-updatelists

      Pi-hole's Lists Updater by Jack'lul
 https://github.com/jacklul/pihole-updatelists

Opened gravity database: /etc/pihole/gravity.db (11.66 MB)
```

**Comment by jacklul** [comment]
Oh! That one was reported before with Fedora.
I will put some info on it in the readme! Thanks!
