### ISSUE TITLE
Watchtower | Could not do a head request for...

### ISSUE THREAD

**Issue by tordenflesk** [jacklul/pihole-updatelists#127]
Could not do a head request for "jacklul/pihole:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"
Found new jacklul/pihole:latest image (1f68b2f0789f)

related issue: https://github.com/containrrr/watchtower/issues/1528

**Comment by jacklul** [comment]
There's been a lot of issues with Dockerhub lately
I have no idea how I can fix this as it looks like Dockerhub expects some kind of authentication now when doing queries to their API
