### ISSUE TITLE
Root priviliges required

### ISSUE THREAD

**Issue by Kopernikus1979** [jacklul/pihole-updatelists#128]
Hi,

When I run pihile-updatelists (or  /usr/local/sbin/pihole-updatelists) I alaways get the warning I need to run it with root privileges.
So "sudo pihile-updatelists", and this works, however will the scheduler work?
Before I could run "pihile-updatelists" without sudo, I don't now what's changed?

**Comment by jacklul** [comment]
> Hi,
> 
> When I run pihile-updatelists (or /usr/local/sbin/pihole-updatelists) I alaways get the warning I need to run it with root privileges. So "sudo pihile-updatelists", and this works, however will the scheduler work? Before I could run "pihile-updatelists" without sudo, I don't now what's changed?

Scheduled task will always run as root unless specified otherwise.
Previously when executing `pihole-updatelists` without `sudo` it silently re-launched itself with `sudo pihole-updatelists`, because this is a bad practice this behavior was removed.
