### ISSUE TITLE
Difference between adlists and blacklists URL

### ISSUE THREAD

**Issue by Chillsmeit** [jacklul/pihole-updatelists#129]
Sorry, I'm just a bit confused regarding how to input Adlists and Blacklists and the difference between them.
Firebog is considered an Adlist because it links to several lists? My question is, is oisd.nl a blacklist then?
What about this one? https://raw.githubusercontent.com/blocklistproject/Lists/master/smart-tv.txt

Here's an example of my .conf
```

; Pi-hole's Lists Updater by Jack'lul
; https://github.com/jacklul/pihole-updatelists
; For a full list of available variables please see the readme.

; Remote list URL containing list of adlists to import
; URLs to single adlists are not supported here!
ADLISTS_URL="https://v.firebog.net/hosts/lists.php?type=nocross https://unbound.oisd.nl/"

; Remote list URL containing exact domains to whitelist
WHITELIST_URL="https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt"

; Remote list URL containing regex rules for whitelisting
REGEX_WHITELIST_URL=""

; Remote list URL containing exact domains to blacklist
; This is specifically for handcrafted lists only, do not use regular blocklists here!
BLACKLIST_URL="https://raw.githubusercontent.com/blocklistproject/Lists/master/smart-tv.txt https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt>

; Remote list URL containing regex rules for blacklisting
REGEX_BLACKLIST_URL="https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list"

```

**Comment by jacklul** [comment]
`BLACKLIST_URL` is meant for handcrafted lists - for example when you manage multiple Pi-hole instances where you block some domains manually and want all the instances to block those.
You should not use any lists from firebog or oisd here as it will reduce Pi-hole's performance, only add those to adlists.

**Comment by Chillsmeit** [comment]
Yeah, I read the config file but was a bit confused as to where I'd put single Adlists in the conf file.
That's why I was putting them in the blacklist section
I was basically trying to use the conf file for everything. 
I'll put https://unbound.oisd.nl/ and https://raw.githubusercontent.com/blocklistproject/Lists/master/smart-tv.txt in the Pi-hole web UI
Thanks for the info!
