### ISSUE TITLE
Is there some caching going on?

### ISSUE THREAD

**Issue by p1r473** [jacklul/pihole-updatelists#13]
I keep having an issue where if I update my GitHub files, then run the script, the script still sees old entries

For example, here is a screenshot.
Top- I am running the script, after recently deleting a bunch of adlists.
Bottom- is a realtime view of my adlist.
The script is trying to grab old entries.
I know that there are ratelimits that Github imposes that the raw.githubusercontent.com sometimes ratelimits when you make edits, but when I view raw in the browser, the entries are gone

However, if I wait a minute, or run it a few times, it eventually works. I am wondering id you are doing any caching of the lists, or if this is GitHub serving up old content sometimes?

![image](https://user-images.githubusercontent.com/9235633/80314522-fc52a780-87bf-11ea-8307-ce70d8db27e5.png)

**Comment by p1r473** [comment]
I think this is actually GitHub not propogating all of the changes to all the CDNs right away, so my browser may see an up to date list, but the script got the old one maybe.
@jacklul feel free to add your 2 cents

**Comment by jacklul** [comment]
There are server side caches for github, if you're force-pushing to your repository you might be seeing old version for a long time when using raw.githubusercontent.com

**Comment by p1r473** [comment]
Thank you!~

**Comment by p1r473** [comment]
For those experiencing the same thing as me, check out the project at https://gitcdn.link or https://gitcdn.xyz/
