### ISSUE TITLE
Add Hostname

### ISSUE THREAD

**Issue by stevefxp1** [jacklul/pihole-updatelists#130]
Hello,

Could you please add [hostname](hostname: pihole) to your yml, so I do not have to do it via template. Without it your hostname is a 12 digit name. I do not see any way, via an environment variable, to change this.

Thanks,
Steve

**Comment by bakerboy448** [comment]
https://docs.docker.com/config/containers/container-networking/#ip-address-and-hostname

**Comment by jacklul** [comment]
I'm a little confused - what prevents you from setting it in your yml?
I do not force `docker-compose.yml` in any way.

**Comment by stevefxp1** [comment]
> https://docs.docker.com/config/containers/container-networking/#ip-address-and-hostname

Yes I have used that in my own yml and template. It would be easier if it were in the original image. I am using Portainer and it does not have any place to specify this, without creating my own template.

**Comment by stevefxp1** [comment]
> I'm a little confused - what prevents you from setting it in your yml? I do not force `docker-compose.yml` in any way.

When in Portainer I cannot add anything to your image, so my only way to do it is use my own yml and add it. Yes it works and what I am running on now, but it would be simpler to just use your image if it had it by default.

**Comment by bakerboy448** [comment]
portainer allows you to set env vars - why can't you set it in portainer?

**Comment by stevefxp1** [comment]
> portainer allows you to set env vars - why can't you set it in portainer? or set it as an env var in your yml?

It seems Portainer does not carry over the hostname variable. I am going to test one more time. I could have missed it.

**Comment by stevefxp1** [comment]
> portainer allows you to set env vars - why can't you set it in portainer? or set it as an env var in your yml?
> 
> `hostname: pihole` in the yml i believe

Yes I am using it in my own yml
