### ISSUE TITLE
Feature request: list inserted/disabled

### ISSUE THREAD

**Issue by p1r473** [jacklul/pihole-updatelists#133]
Feature request: list inserted/disabled
ex: `Processing... 268 exists, 2 inserted, 6 disabled`
Would love to know which they are!

**Comment by jacklul** [comment]
That feature already exists:
- `--verbose` command line argument
- `VERBOSE=true` in the config

**Comment by p1r473** [comment]
Thanks!!

**Comment by p1r473** [comment]
@jacklul is there any way to not show the "exists" stuff but just show added/removed?
