### ISSUE TITLE
invalid blacklists

### ISSUE THREAD

**Issue by TMTYD** [jacklul/pihole-updatelists#134]
Hi

in Pihole I always get the message that this blacklist is no longer valid, how can I permanently remove it?

```
Adlist with ID 57 was inaccessible during last gravity run.
https://v.firebog.net/hosts/Shalla-mal.txt

Adlist with ID 73 was inaccessible during last gravity run.
https://www.joewein.net/dl/bl/dom-bl-base.txt
```

**Comment by jacklul** [comment]
Removing will only make it to be re-added by my script.
You can however disable it via the web UI and empty the comment field (you can put anything in the comment field as long it doesn't contain "Managed by pihole-updatelists" string).

**Comment by TMTYD** [comment]
Ok thanks, yes the lists are dead, how and where do I report this to the supervisor?

**Comment by jacklul** [comment]
https://github.com/WaLLy3K/wally3k.github.io
