### ISSUE TITLE
Request to introduce the ability to modify command to update gravity in the configuration file

### ISSUE THREAD

**Issue by CyanMatter** [jacklul/pihole-updatelists#136]
Hi,

I have Pi-hole installed as a Docker container. So when I attempted a first run after installing and configuring pihole-updatelists as per the instructions in the readme, the program couldn't find the command to update gravity at `/usr/local/bin/pihole updateGravity`. To update gravity in my case, I believe the program should use `docker exec` to use the command in the running container.

The path to updateGravity is set at [line 2642](https://github.com/jacklul/pihole-updatelists/blob/ec48ffb32bd72ee2fe4c68eeb89b97556a4db17a/pihole-updatelists.php#L2642). It would benefit me if I could set the command to update gravity in the configuration file. Similarly, I was able to set the path to `gravity.db` to its location in the volume by modifying GRAVITY_DB.

Swapping `CONTAINER` with the name of the container, I fixed it by changing line 2642 to:
`$command = 'docker exec CONTAINER pihole updateGravity';`
However, this fix will not persist when I update the program. If I update, I think I'll write a command at `/usr/local/bin/` that simply relays the command from pihole-updatelists to the correct destination.

And please correct me if I overlooked something!

**Comment by jacklul** [comment]
You should probably look here: https://github.com/jacklul/pihole-updatelists#install-with-docker

**Comment by CyanMatter** [comment]
I believe using your image will solve this problem, but unfortunately it's not an option for me. I'd like to keep using [cbcrowe/pihole-unbound](https://hub.docker.com/r/cbcrowe/pihole-unbound) as an all-around DNS solution in one container.

**Comment by jacklul** [comment]
I am pretty sure you could do this in that case:
```Dockerfile
FROM cbcrowe/pihole-unbound:latest

RUN apt-get update && apt-get install -Vy wget php-cli php-sqlite3 php-intl php-curl

RUN wget -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/install.sh | bash -s docker
```

**Comment by jacklul** [comment]
Just a note: I've added `PIHOLE_CMD` which can be also used to achieve what you mentioned.
Setting it to `docker exec CONTAINER pihole` will be equivalent to `$command = 'docker exec CONTAINER pihole updateGravity';`.
