### ISSUE TITLE
Issues running on Arch Linux

### ISSUE THREAD

**Issue by chriscoxe** [jacklul/pihole-updatelists#137]
I had to do the following two workarounds in order to successfully run it on Arch Linux:
1. `sudo pihole-updatelists` assumes that the directory `/etc/bash_completion.d` already exists. I had to create it (I did `sudo mkdir /etc/bash_completion.d`), otherwise it fails with an error message about it when I run it. Maybe it should create it if it doesn't already exist?
2. `sudo pihole-updatelists` fails with an error message on my OS (Arch Linux) because it assumes `pihole` exists at `/usr/local/bin/pihole`. On my OS (Arch Linux), it exists at `/usr/bin/pihole`, not `/usr/local/bin/pihole`. To work around this, I did `sudo ln -s /usr/bin/pihole /usr/local/bin/pihole`. I'm not sure if this way was the proper/best way to work around it, so I'm not sure what the best way to solve this in `pihole-updatelists` would be?

After I made those two changes, it started working.

If it matters, FYI I'm using pi-hole-standalone which I installed via the instructions at https://wiki.archlinux.org/title/Pi-hole.

Thanks for writing/maintaining this great tool - it's just what I wanted and seems to be working fine after the workarounds.

**Comment by jacklul** [comment]
> 1. `sudo pihole-updatelists` assumes that the directory `/etc/bash_completion.d` already exists. I had to create it (I did `sudo mkdir /etc/bash_completion.d`), otherwise it fails with an error message about it when I run it. Maybe it should create it if it doesn't already exist?

I believe you meant install script instead. Fixed in 3ecf053cef17ae316c0a96c4acf0c9332afdc2ea.

> 2\. `sudo pihole-updatelists` fails with an error message on my OS (Arch Linux) because it assumes `pihole` exists at `/usr/local/bin/pihole`. On my OS (Arch Linux), it exists at `/usr/bin/pihole`, not `/usr/local/bin/pihole`. To work around this, I did `sudo ln -s /usr/bin/pihole /usr/local/bin/pihole`. I'm not sure if this way was the proper/best way to work around it, so I'm not sure what the best way to solve this in `pihole-updatelists` would be?

Added `PIHOLE_CMD` config variable, simply set it to `/usr/bin/pihole` in the config file. (388d3b26a9704b24f24af3244690010dadf57b4a)
Your symlink will no longer be required once you set that variable.

_Tagging https://github.com/jacklul/pihole-updatelists/issues/136 as something similar was requested there._

**Comment by jacklul** [comment]
I'm curious: does the Pi-hole official installer not work on Arch?

**Comment by chriscoxe** [comment]
I haven't tried - I following the official instructions for Arch Linux at https://wiki.archlinux.org/title/Pi-hole but I didn't need pihole's server nor GUI so (in true Arch Linux fashion...) I installed the pihole standalone variant using the instructions on that page. For packages, I tend to follow the Arch-specific instructions if Arch Linux has a page about a package.

Some other feedback/queries based on my experience installing for pihole standalone (on Arch Linux) in case you're interested:
- The README.md says:
> If you don't plan on updating adlists or want to keep Pi-hole's gravity update schedule you should skip this section and set UPDATE_GRAVITY=false in the configuration file.
Do you mean "updating", or "editing"?
- My impression is that you don't want pihole to update gravity if `pihole-updatelists` is in effect. If I am correct, is it simply because it's unnecessary, or is it more serious, such as because e.g. it could cause corruption etc if it happens at the same time that `pihole-updatelists` (running manually) or its schedule updates gravity?
- I installed pihole standalone but on my OS anyway (Arch Linux), it seems to use systemd for scheduling, not cron. The instructions under section "Disable default gravity update schedule" only mention cron, not systemd, so I didn't know what to do, and I was unclear what harm might be caused if `pihole-updatelists` and pihole updated gravity at the same time, so I decided to risk it and not change anything (let them both individually update gravity when run manually or scheduled). Any comment?

**Comment by jacklul** [comment]
> * My impression is that you don't want pihole to update gravity if `pihole-updatelists` updates gravity. If I am correct, is it simply because it's unnecessary, or is it more serious, such as because e.g. it could cause corruption etc if it happens at the same time that `pihole-updatelists` (running manually) or its schedule updates gravity?
> Do you mean "updating", or "editing"?

I've seen people using my tool just to add the lists in bulk in the past and sync it from time to time manually or those who want to keep the original schedule.
You can use my tool to not touch adlists at all and only update other lists, gravity update is only required when updating adlists.

> * I installed pihole standalone but on my OS anyway (Arch Linux), it seems to use systemd for scheduling, not cron. The instructions under section "Disable default gravity update schedule" only mention cron, not systemd, so I didn't know what to do, and I was unclear what harm might be caused if `pihole-updatelists` and pihole updated gravity at the same time, so I decided to risk it and not change anything (let them both individually update gravity when run manually or scheduled). Any comment?

No matter what system you're using Pi-hole installer installs a crontab file at `/etc/cron.d/pihole`, if you installed manually you're missing some of them.

**Comment by chriscoxe** [comment]
So the "Disable default gravity update schedule" section is optional, not required?

I gather that "pihole standalone" is an Arch alteration of pihole for a standalone PC, and doesn't use cron. So, it's not really "pihole" as such and I wouldn't expect `pihole-updatelists` to support it, although it's nice that it appears to work regardless.

**Comment by jacklul** [comment]
> So the "Disable default gravity update schedule" section is optional, not required?

Is not required, but recommended as there is no point in running gravity update twice in  two days.

These are the default crontab entries: https://github.com/pi-hole/pi-hole/blob/master/advanced/Templates/pihole.cron
As you can see you're losing the update checker and log rotation functionality.
