### ISSUE TITLE
Script does not detect systemd on Proxmox LXC container

### ISSUE THREAD

**Issue by mschabhuettl** [jacklul/pihole-updatelists#138]
Hello!

I've noticed that the script does not install the `pihole-updatelists.timer` file on Proxmox LXC running Pi-Hole.

I've used [tteck](https://github.com/tteck/Proxmox)'s LXC install script for Pi-Hole (https://tteck.github.io/Proxmox/) running Debian 12.

`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/pihole.sh)"`

Cheers!

**Comment by jacklul** [comment]
The install script checks for alive `systemd` process, you can force systemd install by [adding `systemd` parameter to install script](https://github.com/jacklul/pihole-updatelists/blob/master/install.sh#L38).

**Comment by mschabhuettl** [comment]
Awesome @jacklul thank you!
