### ISSUE TITLE
Exception: SQLSTATE[23000]: Integrity constraint violation

### ISSUE THREAD

**Issue by RichardBeisser** [jacklul/pihole-updatelists#140]
Hello,
how can I handle errors mentioned in subject?
I think, lists can contain errors. So it would be great if your script detect the incorrect lines and ignore them

lists (whitelist) which i want to use and which cause the error:
https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/whitelist/master/domains.list
https://raw.githubusercontent.com/EnergizedProtection/unblock/master/basic/formats/domains.txt
https://raw.githubusercontent.com/fabriziosalmi/blacklists/main/whitelist.txt

complete error-message:
`Fetching WHITELIST from 'https://raw.githubusercontent.com/fabriziosalmi/blacklists/main/whitelist.txt'... done (2243 entries)
Processing...Exception: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: domainlist.domain, domainlist.type
`
my config:
[pihole-updatelists.conf.txt](https://github.com/jacklul/pihole-updatelists/files/12922193/pihole-updatelists.conf.txt)

**Comment by RichardBeisser** [comment]
> Hello, can you try develop branch ? 

just made an upgrade to develop branch. It seems that you have fixed the problem in develop branch.
When does you make develop branch to official?

**Comment by jacklul** [comment]
The fix should be on master now!
