### ISSUE TITLE
Question: all Domains of a certain list disabled

### ISSUE THREAD

**Issue by RichardBeisser** [jacklul/pihole-updatelists#141]
Hello,

see my config-file,

[pihole-updatelists.conf.txt](https://github.com/jacklul/pihole-updatelists/files/12927310/pihole-updatelists.conf.txt)

 all domains of  anudeepND optional-list.txt were added disabled.
I dont understand why.

Thanks

**Comment by jacklul** [comment]
Could you try `develop` branch? It seems to be fixed now!

**Comment by RichardBeisser** [comment]
> Could you try `develop` branch? It seems to be fixed now!

I can confirm it.
Thanks for fast fixxing.
