### ISSUE TITLE
Installation path /usr/local/sbin, path doesnt exist on Raspbian

### ISSUE THREAD

**Issue by RichardBeisser** [jacklul/pihole-updatelists#142]
Hello,

the install.sh want to install your script in /usr/local/sbin/ but on Raspian this path doesnt exist.
You have to create this folder manually first.
Is there a reason why you select this special folder for installation?
Does your install.sh support custom installation folder?

Thanks.

**Comment by jacklul** [comment]
Because it's a directory for admin utilities not managed by any package manager.

It's weird that it doesn't exist by default, I'll add it do install script.
