### ISSUE TITLE
pihole-updatelists unable to find host following initail install on host running unbound

### ISSUE THREAD

**Issue by paulrobinsontkd** [jacklul/pihole-updatelists#144]
I have both pihole and unbound installed on the same docker image using https://github.com/chriscrowe/docker-pihole-unbound/tree/main/one-container

I built a custom docker image adding pihole-updatelists

It seems however the pihole-updatelists is failing to resolve hosts on subsequent reboots following initial install.  The initial install worked fine and downloaded the additional block lists however on subsequent reboots of the docker container it is failing to resolve the host.

I think the issue is the ordering of services starting and potentially unbound not being started before it attempts to perform the updates. See log file below:-

services-up: info: copying legacy longrun unbound (no readiness notification)
s6-rc: info: service legacy-services successfully started
Starting unbound
Disabled default gravity update schedule in /etc/cron.d/pihole

      Pi-hole's Lists Updater by Jack'lul
 https://github.com/jacklul/pihole-updatelists

Opened gravity database: /etc/pihole/gravity.db (65.09 MB)

Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... Could not resolve host: v.firebog.net

Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... Could not resolve host: raw.githubusercontent.com

Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... Could not resolve host: raw.githubusercontent.com

Finished with 3 error(s) in 30.04 seconds.
[~] #

**Comment by jacklul** [comment]
The installer puts the execution of the script right before `_postFTL`, so at that point `pihole-FTL` should be running and for it to correctly resolve DNS you need to start unbound way earlier.

Some people simply added a fallback DNS setting to the docker compose and that fixed the startup issue:
```
dns:
  - 127.0.0.1
  - 1.1.1.1
```

**Comment by paulrobinsontkd** [comment]
I created a new docker image from the official pihole image just to rule it out and added unbound via docker file.  When i start without your update script unbound and pihole services all start correctly

Starting unbound
  [i] Creating new gravity database
  [i] Migrating content of /etc/pihole/adlists.list into new database
  [✗] DNS resolution is currently unavailable
  [✓] DNS resolution is now available

  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [✓] Creating new gravity databases
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 160200 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "0.0.0.0"


  [✓] Building tree
  [✓] Swapping databases
  [✓] The old database remains available
  [i] Number of gravity domains: 160200 (160200 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Cleaning up stray matter

  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [i] Pi-hole blocking will be enabled
  [i] Enabling blocking
  [✓] Pi-hole Enabled

It takes anywhere from 10 - 15 seconds before unbound is started from the looks of it.  

I then recreated the custom docker image based off official pihole adding in the update scripts to my dockerfile
RUN wget -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/install.sh | bash -s docker

On first run unbound starts and all pihole services start before executing update script

Starting unbound
Disabled default gravity update schedule in /etc/cron.d/pihole
Gravity database not found - running 'pihole -g' command...
  [i] Creating new gravity database
  [i] Migrating content of /etc/pihole/adlists.list into new database
  [✗] DNS resolution is currently unavailable
  [✓] DNS resolution is now available

  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [✓] Creating new gravity databases
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 160200 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "0.0.0.0"


  [✓] Building tree
  [✓] Swapping databases
  [✓] The old database remains available
  [i] Number of gravity domains: 160200 (160200 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Cleaning up stray matter

  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [i] Pi-hole blocking will be enabled
  [i] Enabling blocking
  [✓] Pi-hole Enabled

      Pi-hole's Lists Updater by Jack'lul
 https://github.com/jacklul/pihole-updatelists

Opened gravity database: /etc/pihole/gravity.db (9.38 MB)

Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... done (31 entries)
Processing... 31 inserted

Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... done (191 entries)
Processing... 191 inserted

Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... done (14 entries)
Processing... 14 inserted

I restarted docker and the start up sequence seems different and the script looks to be executing prior to unbound starting

Starting unbound

      Pi-hole's Lists Updater by Jack'lul
 https://github.com/jacklul/pihole-updatelists

Opened gravity database: /etc/pihole/gravity.db (65.11 MB)

Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... Could not resolve host: v.firebog.net

Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... Could not resolve host: raw.githubusercontent.com

Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... Could not resolve host: raw.githubusercontent.com

Finished with 3 error(s) in 30.03 seconds.

I tried adding the dns flags to the docker compose file but it made zero difference.

Unfortunately my knowledge of debian services and timers is next to nothing, was looking if i can move unbound to start before pihole but have no idea how to do it. 

I was hoping to have a custom docker image which installed pihole/unbound and update scripts which i could run once a new release comes out and saves me lots of effort post config.  Might have to rethink and seperate out pihole and unbound if i can't get it to work.

**Comment by jacklul** [comment]
Try using development branch, it will now wait for DNS `pi.hole` domain to be resolvable

**Comment by paulrobinsontkd** [comment]
Have deployed the script in a custom docker container with the following RUN statement using develop branch
RUN wget -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/develop/install.sh | bash -s docker

I don't however think it has deployed the amended code as it is still failing.

I also do not see the echo's that are present in the updated docker.sh when pihole restarts for the second time
echo "Waiting for DNS resolution to be available..."


Opened gravity database: /etc/pihole/gravity.db (65.13 MB)

Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... Could not resolve host: v.firebog.net

Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... Could not resolve host: raw.githubusercontent.com

Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... Could not resolve host: raw.githubusercontent.com

Finished with 3 error(s) in 30.03 seconds.


[admin@qnap ~]# docker exec -it pihole bash
root@pihole:/# cat /var/log/pihole-updatelists-boot.log
[2023-11-30 17:59:46 UTC] [INFO]        Pi-hole's Lists Updater by Jack'lul started
[2023-11-30 17:59:46 UTC] [INFO]        Opened gravity database: /etc/pihole/gravity.db (65.13 MB)
[2023-11-30 17:59:46 UTC] [INFO]        Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'...
[2023-11-30 17:59:56 UTC] [ERROR]       Could not resolve host: v.firebog.net
[2023-11-30 17:59:56 UTC] [INFO]        Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'...
[2023-11-30 18:00:06 UTC] [ERROR]       Could not resolve host: raw.githubusercontent.com
[2023-11-30 18:00:06 UTC] [INFO]        Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'...
[2023-11-30 18:00:16 UTC] [ERROR]       Could not resolve host: raw.githubusercontent.com
[2023-11-30 18:00:16 UTC] [INFO]        Finished with 3 error(s) in 30.03 seconds.
root@pihole:/#

**Comment by jacklul** [comment]
> mkdir: cannot create directory '/etc/pihole-updatelists': File exists

Installation failed here.

**Comment by paulrobinsontkd** [comment]
@jacklul sorted, yes you was correct.  

It would of likely been resolving pi.hole from the hosts file, when i changed the check to `PHUL_DNSCHECK_DOMAIN=firebog.net` It now waiting long enough for the DNS resolution to work and the update script executes fine.

```
Starting unbound
Waiting for DNS resolution to be available...

      Pi-hole's Lists Updater by Jack'lul
 https://github.com/jacklul/pihole-updatelists

Opened gravity database: /etc/pihole/gravity.db (65.14 MB)

Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... done (31 entries)
Processing... 31 exists

Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... done (191 entries)
Processing... 191 exists

Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... done (14 entries)
Processing... 14 exists

Finished successfully in 0.3 seconds.
```

When i run a debug of unbound it seems it is reloading all the cache that is taking the time for the startup of DNS.  Once up and running i don't expect the container to be stopped frequently but its nice to know that if it is restarted the update script will run correctly.

Many thanks for all your help and support to get this to work.

**Comment by jacklul** [comment]
I've modified the commit to use `pi-hole.net` by default and pushed to the master branch.

**Comment by paulrobinsontkd** [comment]
Thanks, have deployed from master and can confirm it is working 👍
