### ISSUE TITLE
Script doesnt respect if entry is already present

### ISSUE THREAD

**Issue by RichardBeisser** [jacklul/pihole-updatelists#145]
Hello,

it seems that the script doesnt check if an entry for a certain domain is already defined.
How can I enable this behaviour?

There should be a running mode which
a) only add entries when no entry for a domain ist set manually
b) modify and delete only entries which were created by the script.

I think the only way to mark an entry as managed by your script is to use the comment

Thanks

**Comment by jacklul** [comment]
https://github.com/jacklul/pihole-updatelists?tab=readme-ov-file#migrating-lists-and-domains

**Comment by RichardBeisser** [comment]
> https://github.com/jacklul/pihole-updatelists?tab=readme-ov-file#migrating-lists-and-domains

I read this. This refer only that your script will not overwrite comment-field if entry is already exists.
But it seems that the script existing group-assigment

Example: see attached config-file + youtube.com
[pihole-updatelists.conf.txt](https://github.com/jacklul/pihole-updatelists/files/13694192/pihole-updatelists.conf.txt)
youtube.com is whitelisted for group-id 3 only. comment for youtube.com = "my comment"
After running the script, youtube.com has still the comment "my comment" (that is very good!), but groups has been changed from 3 to 0+1, according the config-file.
There should be an option saying the script that it shall change nothing if entry already exists and is not set by the script.

another point, a feature request:
there should be a ignore-option for whitelisting for certain domains
a blacklisted entry can be "overwritten" by setting a whitelist-entry, because wl has a higher priority. It would be great if you can exclude certain domains / regex from whitelisting.

In words of your options:
WHITELIST_IGNORE	" " 	
REGEX_WHITELIST_IGNORE   " "

Thanks a lot.

**Comment by jacklul** [comment]
> Example: see attached config-file + youtube.com
> [pihole-updatelists.conf.txt](https://github.com/jacklul/pihole-updatelists/files/13694192/pihole-updatelists.conf.txt)
> youtube.com is whitelisted for group-id 3 only. comment for youtube.com = "my comment"
> After running the script, youtube.com has still the comment "my comment" (that is very good!), but groups has been changed from 3 to 0+1, according the config-file.

I will look into this when I can

> another point, a feature request: there should be a ignore-option for whitelisting for certain domains a blacklisted entry can be "overwritten" by setting a whitelist-entry, because wl has a higher priority. It would be great if you can exclude certain domains / regex from whitelisting.
> 
> In words of your options: WHITELIST_IGNORE " " REGEX_WHITELIST_IGNORE " "

I rather not add a functionality like this - you could wget the list and filter it with sed then provide local path in the config file instead.

**Comment by jacklul** [comment]
Check if the newest develop version fixes mentioned issue.
