### ISSUE TITLE
Modification of pihole-FTL.service file

### ISSUE THREAD

**Issue by cmonty14** [jacklul/pihole-updatelists#153]
Hi,
according to your instructions one should [disable default gravity update schedule](https://github.com/jacklul/pihole-updatelists?tab=readme-ov-file#disable-default-gravity-update-schedule).

However I'm not sure if it makes sense to modify the default  _pihole-FTL.service_ file as this change could be overwritten by a new deployment of _pihole_.
In addition, this [service file](https://github.com/pi-hole/pi-hole/blob/master/advanced/Templates/pihole-FTL.systemd) contains this
```
ExecStartPre=/opt/pihole/pihole-FTL-prestart.sh
```
already that is another bash script executing different commands.

Would it makes sense to use a similar approach to modify cronjob _/etc/cron.d/pihole_?

**Comment by jacklul** [comment]
`systemctl edit pihole-FTL.service` creates override file which is merged with the main one.
You can have multiple `ExecStartPre`, per systemd's documentation.
