### ISSUE TITLE
Updating comment in gravity.db fails

### ISSUE THREAD

**Issue by cmonty14** [jacklul/pihole-updatelists#154]
Hi,
I have manually added 10 adlists to Pihole; all use comment like
firebog.net - Suspicious List 1
firebog.net - Suspicious List 2
etc.

Running command `sudo sqlite3 /etc/pihole/gravity.db "UPDATE adlist SET comment = 'Managed by pihole-updatelists' WHERE comment LIKE '%Firebog |%' OR comment LIKE '%[ph5lt]' OR comment LIKE '%firebog |%'"` does not update the comment.

Can you please advise how to fix this?

**Comment by jacklul** [comment]
The command only supports comment created by pihole5-list-tool, as mentioned line above them in the readme.

In your case correct match would be '%firebog.net - %'.
