### ISSUE TITLE
Regex keeps toggling

### ISSUE THREAD

**Issue by p1r473** [jacklul/pihole-updatelists#16]
Hi Jack,

I recently added some regexes.
Every time I run the script, the regex gets toggled.
So I run the script once, and all regexes are disbled. I run it again, and all regexes are enabled. I run it again, and all regexes are disabled again.

Here is the output:
https://pastebin.com/juLu7nUX

Example

Run 1:
```
SQL Query: UPDATE `domainlist` SET `enabled` = 1 WHERE `id` = 1246
Enabled: ^https?://([a-za-z0-9.-]*\.)?.doubleclick(\.\w{2}\.\w{2}|\.\w{2,4})/
```
Run 2:
```
SQL Query: UPDATE `domainlist` SET `enabled` = 0 WHERE `id` = 1246
Disabled: ^https?://([a-za-z0-9.-]*\.)?.doubleclick(\.\w{2}\.\w{2}|\.\w{2,4})/
```
Run 3:
```
SQL Query: UPDATE `domainlist` SET `enabled` = 1 WHERE `id` = 1246
Enabled: ^https?://([a-za-z0-9.-]*\.)?.doubleclick(\.\w{2}\.\w{2}|\.\w{2,4})/
```

**Comment by jacklul** [comment]
This is weird issue, and happens only with those regex rules.
There is some kind of bug with `array_diff()` function...

**Comment by p1r473** [comment]
I'm just glad it wasn't a user error this time ^^

**Comment by jacklul** [comment]
Should be fixed, check

**Comment by p1r473** [comment]
Sure, just let me know when :)
Thanks for fixing it!

**Comment by jacklul** [comment]
Now, check and make sure nothing is getting messed up with lower/upper case

**Comment by p1r473** [comment]
Looks like its fixed
To test the upper/lower case, I tried changing some lowercase to caps. 
I think it worked. Let me know if this isn't what you wanted

```
Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/p1r473/hosts/master/blacklist-regex.txt'... done (46 entries)
Processing...
SQL Query: SELECT * FROM `domainlist` WHERE `enabled` = 1 AND `type` = 3
SQL Query: UPDATE `domainlist` SET `enabled` = 0 WHERE `id` = 1311
Disabled: ^(.+[_.-]?)?adchoice.*
SQL Query: INSERT INTO `domainlist` (domain, type, enabled, comment) VALUES ("^(.+[_.-]?)?ADCHOICE.*", 3, 1, "Managed by pihole-updatelists")
Inserted: ^(.+[_.-]?)?ADCHOICE.*
```
