### ISSUE TITLE
Sending reload signal to Pi-hole's DNS server

### ISSUE THREAD

**Issue by p1r473** [jacklul/pihole-updatelists#17]
Hi Jacklul
In the latest PiHole 5.0, the following step of your script is not needed
```Sending reload signal to Pi-hole's DNS server```

With the new database system, we can add and remove whitelists without needing to use ```pihole restartdns```

I believe we can remove this part of the script.

**Comment by jacklul** [comment]
This actually does not run `pihole restartdns` but sends `SIGRTMIN` signal to it.
I grabbed that signal from pihole scripts and they seem to send it after every add/remove operation.

**Comment by p1r473** [comment]
Oh, I see, I thought only it runs restartdns.

I tried to find any reference of this code in the 5.0 scripts and could not find anything.
```
root@TinkerBoardS:/opt/pihole # grep -Ril "SIGRTMIN" /opt/pihole
root@TinkerBoardS:/opt/pihole # grep -Ril "explode" /opt/pihole
root@TinkerBoardS:/opt/pihole # grep -Ril "posix_kill" /opt/pihole
```

**Comment by p1r473** [comment]
Did find this though:
```
root@TinkerBoardS:/opt/pihole # grep -Ril "posix_kill" /etc/.pihole
root@TinkerBoardS:/opt/pihole # grep -Ril "explode" /etc/.pihole
/etc/.pihole/advanced/index.php
root@TinkerBoardS:/opt/pihole # grep -Ril "SIGTMIN" /etc/.pihole
root@TinkerBoardS:/opt/pihole #
```

**Comment by jacklul** [comment]
https://github.com/pi-hole/pi-hole/blob/release/v5.0/pihole#L113

**Comment by p1r473** [comment]
Whoops, I guess I spelled SIGRTMIN wrong  haha!
Good find, thanks!
