### ISSUE TITLE
AD lists

### ISSUE THREAD

**Issue by evlsmurf** [jacklul/pihole-updatelists#18]
In regards to the one of the lists you mention does it allow me to use https://v.firebog.net/hosts/lists.php?type=tick as a list or do i need to list all the list individually from that on say my github and then put github link in config?

**Comment by jacklul** [comment]
`ADLISTS_URL` must point to file contaning list of adlists. (just like `adlists.txt` before)

**Comment by evlsmurf** [comment]
So in other words take https://v.firebog.net/hosts/lists.php?type=tick copy/paste all lists within it to a adlist.txt or github add url/text file location to ADLISTS_URL section.

Sry just last script i used pulled all url's from that link and didn't need to copy them script did it all just for sake of clarity wanted to know.

**Comment by jacklul** [comment]
I believe `ADLISTS_URL="https://v.firebog.net/hosts/lists.php?type=tick"` is what you want

**Comment by evlsmurf** [comment]
Ok that's all i need to know so it will pull all links within that link

so creating a list like this on github and using github url it will work 
https://v.firebog.net/hosts/lists.php?type=tick
https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_all.list
https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list
https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt

**Comment by jacklul** [comment]
> Ok that's all i need to know so it will pull all links within that link
> 
> so creating a list like this on github and using github url it will work
> https://v.firebog.net/hosts/lists.php?type=tick
> https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_all.list
> https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list
> https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
> https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt

If you create a list like this entries from `https://v.firebog.net/hosts/lists.php?type=tick` won't be pulled because it will assume `https://v.firebog.net/hosts/lists.php?type=tick` is an adlist, not list of adlists.

**Comment by evlsmurf** [comment]
understood thanks!

**Comment by jacklul** [comment]
I've reimplemented the feature, it seems to work.

You can basically do something like this now:
```bash
ADLISTS_URL="https://v.firebog.net/hosts/lists.php?type=tick
https://raw.githubusercontent.com/you/adlists/master/my_adlists.txt"
```
And it will fetch both the lists. merge them and insert entries to the database.
