### ISSUE TITLE
Changing comments

### ISSUE THREAD

**Issue by p1r473** [jacklul/pihole-updatelists#20]
Hi Jack,
I think I found a minor bug.
If you change the comment for entries, I don't think it is getting updated in the PiHole database for existing entries.
This leaves some of the comments as the new comment, and some as the old comment.
I changed it to 
```
; Comment string used to know which entries were created by the script
COMMENT="   "
```
![image](https://user-images.githubusercontent.com/9235633/82766912-07195000-9df1-11ea-8ee5-e37dad2f0792.png)

**Comment by jacklul** [comment]
Obviously it won't because it does not know what the old one was.
This has to be done manually by the user.

**Comment by p1r473** [comment]
Thanks Jack!!!
