### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by n0rt0nthec4t** [jacklul/pihole-updatelists#22]
Running on rasbian stretch 

"Sending reload signal to Pi-hole's DNS server...PHP Notice:  Use of undefined constant SIGRTMIN - assumed 'SIGRTMIN' in /usr/local/sbin/pihole-updatelists on line 1184
PHP Warning:  posix_kill() expects parameter 2 to be integer, string given in /usr/local/sbin/pihole-updatelists on line 1184
 failed to send signal"

**Comment by jacklul** [comment]
What's your PHP version? `php --version`

**Comment by n0rt0nthec4t** [comment]
PHP 7.0.33-0+deb9u7 (cli) (built: Feb 16 2020 15:11:40) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u7, Copyright (c) 1999-2017, by Zend Technologies

**Comment by n0rt0nthec4t** [comment]
sudo pihole-updatelists --debug
Acquired process lock through file: /var/lock/pihole-updatelists.lock

      Pi-hole's Lists Updater by Jack'lul     
 https://github.com/jacklul/pihole-updatelists

Checksum: 2cc281b7ecfacd2588bc3ebaade8f959
OS: Linux pihole.local 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l
PHP: 7.0.33-0+deb9u7 NTS
SQLite: 3.16.2
Pi-hole: v5.0-0-g4d25f69 (master)
Web: v5.0-0-gb86e4a3 (master)
FTL: v5.0 (master)
Configuration: array(17) {
  ["CONFIG_FILE"] => string(28) "/etc/pihole-updatelists.conf"
  ["GRAVITY_DB"] => string(22) "/etc/pihole/gravity.db"
  ["LOCK_FILE"] => string(33) "/var/lock/pihole-updatelists.lock"
  ["LOG_FILE"] => string(0) ""
  ["ADLISTS_URL"] => string(47) "https://v.firebog.net/hosts/lists.php?type=tick"
  ["WHITELIST_URL"] => string(82) "https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt"
  ["REGEX_WHITELIST_URL"] => string(0) ""
  ["BLACKLIST_URL"] => string(0) ""
  ["REGEX_BLACKLIST_URL"] => string(71) "https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list"
  ["COMMENT"] => string(29) "Managed by pihole-updatelists"
  ["GROUP_ID"] => int(0)
  ["REQUIRE_COMMENT"] => bool(true)
  ["UPDATE_GRAVITY"] => bool(false)
  ["VACUUM_DATABASE"] => bool(true)
  ["VERBOSE"] => bool(false)
  ["DEBUG"] => bool(true)
  ["DOWNLOAD_TIMEOUT"] => int(60)
}
Options: array(1) {
  ["debug"] => bool(false)
}

Opened gravity database: /etc/pihole/gravity.db (22.49 MB)

Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... done (34 entries)
Processing...
SQL Query: SELECT * FROM `adlist`
SQL Query: SELECT * FROM `adlist` WHERE `enabled` = 1 AND `comment` LIKE "%Managed by pihole-updatelists%"

SQL Query: SELECT * FROM `domainlist`
Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... done (194 entries)
Processing...
SQL Query: SELECT * FROM `domainlist` WHERE `enabled` = 1 AND `type` = 0 AND `comment` LIKE "%Managed by pihole-updatelists%"

SQL Query: SELECT id FROM `domainlist` WHERE `comment` LIKE "%Managed by pihole-updatelists%" AND `enabled` = 1 AND `type` = 2 LIMIT 1
SQL Query: SELECT id FROM `domainlist` WHERE `comment` LIKE "%Managed by pihole-updatelists%" AND `enabled` = 1 AND `type` = 1 LIMIT 1
Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... done (15 entries)
Processing...
SQL Query: SELECT * FROM `domainlist` WHERE `enabled` = 1 AND `type` = 3 AND `comment` LIKE "%Managed by pihole-updatelists%"

Vacuuming database... done (22.49 MB)

Sending reload signal to Pi-hole's DNS server...PHP Notice:  Use of undefined constant SIGRTMIN - assumed 'SIGRTMIN' in /usr/local/sbin/pihole-updatelists on line 1184
PHP Warning:  posix_kill() expects parameter 2 to be integer, string given in /usr/local/sbin/pihole-updatelists on line 1184
 failed to send signal

Memory reached peak usage of 755.2 KB
Finished with 1 error(s) in 31.56 seconds.
Releasing lock and removing lockfile: /var/lock/pihole-updatelists.lock

**Comment by jacklul** [comment]
Update script and check if the error happens again.

Also : output of `kill -l` ?

**Comment by n0rt0nthec4t** [comment]
kill -l 
 1) SIGHUP	 2) SIGINT	 3) SIGQUIT	 4) SIGILL	 5) SIGTRAP
 6) SIGABRT	 7) SIGBUS	 8) SIGFPE	 9) SIGKILL	10) SIGUSR1
11) SIGSEGV	12) SIGUSR2	13) SIGPIPE	14) SIGALRM	15) SIGTERM
16) SIGSTKFLT	17) SIGCHLD	18) SIGCONT	19) SIGSTOP	20) SIGTSTP
21) SIGTTIN	22) SIGTTOU	23) SIGURG	24) SIGXCPU	25) SIGXFSZ
26) SIGVTALRM	27) SIGPROF	28) SIGWINCH	29) SIGIO	30) SIGPWR
31) SIGSYS	34) SIGRTMIN	35) SIGRTMIN+1	36) SIGRTMIN+2	37) SIGRTMIN+3
38) SIGRTMIN+4	39) SIGRTMIN+5	40) SIGRTMIN+6	41) SIGRTMIN+7	42) SIGRTMIN+8
43) SIGRTMIN+9	44) SIGRTMIN+10	45) SIGRTMIN+11	46) SIGRTMIN+12	47) SIGRTMIN+13
48) SIGRTMIN+14	49) SIGRTMIN+15	50) SIGRTMAX-14	51) SIGRTMAX-13	52) SIGRTMAX-12
53) SIGRTMAX-11	54) SIGRTMAX-10	55) SIGRTMAX-9	56) SIGRTMAX-8	57) SIGRTMAX-7
58) SIGRTMAX-6	59) SIGRTMAX-5	60) SIGRTMAX-4	61) SIGRTMAX-3	62) SIGRTMAX-2
63) SIGRTMAX-1	64) SIGRTMAX

**Comment by jacklul** [comment]
Ok so that's weird, we clearly see `SIGRTMIN` is defined but why PHP can't access it by constant is a mystery.

Check if it works after updating my script, I added a check for this case and redefine the signal

**Comment by n0rt0nthec4t** [comment]
Ok, tested updated script and no error now
