### ISSUE TITLE
Super newbie quick question for pihole-updatelists

### ISSUE THREAD

**Issue by popopo099** [jacklul/pihole-updatelists#24]
Hi, I was wondering how to do this part since I'm sort of stuck. 
I've done most of the other steps above successfully, except for the adding this part:
[https://imgur.com/a/ZTxmF7g](https://imgur.com/a/ZTxmF7g)

I also don't know how to disable the update gravity thing. Sorry, super noob.

**Comment by jacklul** [comment]
Everything is in the readme if you read carefully.

> I've done most of the other steps above successfully, except for the adding this part:
> https://imgur.com/a/ZTxmF7g

One section before that there is section about configuration file - `/etc/pihole-updatelists.conf`.

> I also don't know how to disable the update gravity thing. Sorry, super noob.

`/etc/cron.d/pihole`, comment entry with `pihole updateGravity` in it.

**Comment by popopo099** [comment]
I understand, but I'm not sure if I'm missing some prefixes to open them? As I mentioned, I'm a noob and I think your readme could benefit from a little extra helping hand to those that just copy-paste instructions :)

[https://i.imgur.com/Kj0Pthr.jpg](https://i.imgur.com/Kj0Pthr.jpg)

**Comment by jacklul** [comment]
> I understand, but I'm not sure if I'm missing some prefixes to open them? As I mentioned, I'm a noob and I think your readme could benefit from a little extra helping hand to those that just copy-paste instructions :)
> 
> https://i.imgur.com/Kj0Pthr.jpg

Try using `nano` editor to edit those files:
```
sudo nano /etc/pihole-updatelists.conf
sudo nano /etc/cron.d/pihole
```

**Comment by popopo099** [comment]
That worked! Sorry I forgot to reply to this.

Kindly add that to your readme guide so other people can easily do it with no issue :)
