### ISSUE TITLE
Issue With Adlists

### ISSUE THREAD

**Issue by Surdified** [jacklul/pihole-updatelists#25]
Upon running the command "sudo pihole-updatelists" every domain within each adlists file keeps returning as invalid. The adlists I am using are the ticked links on firebog.net.

The image I have attached is an example of what is returned to me upon running "sudo pihole-updatelists"

![image](https://user-images.githubusercontent.com/49766393/85928884-711d8d00-b8a8-11ea-881d-dc8f3e216580.png)

**Comment by jacklul** [comment]
Did you set `ADLISTS_URL` to URL that contains list of adlist URLs?
Please post your configuration, I'm pretty sure mistake is there.

**Comment by Surdified** [comment]
Ah I had it set to the individual adlists themselves, I'll change it to the one you have provided and let you know if it helps.

**Comment by Surdified** [comment]
It's working now, thank you very much.
