### ISSUE TITLE
Updating pihole-updatelists

### ISSUE THREAD

**Issue by evlsmurf** [jacklul/pihole-updatelists#26]
Installed when first release and would like to update to most current how would one go about this? Would running install command again do it or is there a different way?

**Comment by jacklul** [comment]
If you installed the very first version (which was written in bash) you will have to backup your config and remove it as it's format will not work with current script, then just use the install procedure from the readme.

**Comment by evlsmurf** [comment]
it was back in may i installed this so not sure which it was back then

**Comment by jacklul** [comment]
The exact command was used to install the bash version.
Run `head -n 1 /usr/local/sbin/pihole-updatelists` and if it returns `#!/usr/bin/env php` you can just safely run the install command again to update.

**Comment by evlsmurf** [comment]
It does return that thanks!
