### ISSUE TITLE
two quick things...I hope!

### ISSUE THREAD

**Issue by ckouris84** [jacklul/pihole-updatelists#28]
Hello @jacklul 

This is an AWESOME solution to the way I had things set up to pull from text files pre-5.

Two things:

1) Anytime an adlist 404's it kills the entire merging process. Is there a way to catch and continue to the rest of the adslist URLs in the ADSLIST_URL parameter?

2) Is this OK to see when updating (NOTE: I have verbose turned on)

Invalid: 0.0.0.0        www.popadscdn.net
Invalid: 0.0.0.0        www.popcash.net
Invalid: 0.0.0.0        www.popelingmltdiidyr.download
Invalid: 0.0.0.0        www.poponclick.com
Invalid: 0.0.0.0        www.popstrap.com
Invalid: 0.0.0.0        www.poptm.com
Invalid: 0.0.0.0        www.popunder.net
Invalid: 0.0.0.0        www.popunder.ru
Invalid: 0.0.0.0        www.popzila.com
Invalid: 0.0.0.0        www.pornland.mobi
Invalid: 0.0.0.0        www.pornlist.mobi
Invalid: 0.0.0.0        www.pornsponsors.com
Invalid: 0.0.0.0        www.postads24.com
Invalid: 0.0.0.0        www.potionoxfrtmzvr.download
Invalid: 0.0.0.0        www.ppcindo.com
Invalid: 0.0.0.0        www.ppsxqapwsurcoats.review
Invalid: 0.0.0.0        www.pptrk.com
Invalid: 0.0.0.0        www.praptkppltraditors.review
Invalid: 0.0.0.0        www.prchecker.info
Invalid: 0.0.0.0        www.predictivadvertising.com
Invalid: 0.0.0.0        www.prehensivetvrie.download
Invalid: 0.0.0.0        www.premiumhdv.com
Invalid: 0.0.0.0        www.prepareriblef.download
Invalid: 0.0.0.0        www.preplannedpbxggguv.download
Invalid: 0.0.0.0        www.primosearch.com
Invalid: 0.0.0.0        www.pringotrack.com
Invalid: 0.0.0.0        www.prishla.info
Invalid: 0.0.0.0        www.probux.com
Invalid: 0.0.0.0        www.products-and-services.com
Invalid: 0.0.0.0        www.profitreload.com
Invalid: 0.0.0.0        www.projectwonderful.com
Invalid: 0.0.0.0        www.promolnk.com

**Comment by jacklul** [comment]
1. No because in that case that would result in entries from 404'd list to be disabled.
2. Those are invalid entries, did you put adlist as blacklist?

**Comment by ckouris84** [comment]
Thanks for the quick response!

1. Ah, so I noticed if you have a typo in a URL or have a URl with a list of sources that is no longer valid and 404s on you, then the rest of the URLs are not attempted to grab other source lists of URLs with domains. I thought if we were to just use TRUE as the third argument for logging anytime a FALSE is returned by the file_get_contents() for grabbing from those URLs, then the other URL will just continue and that one would not be added. You're saying that a "blank" or null response from a 404'd URL would actually wipe out entries? OK so I'm guessing that when a single source, addressed at a specific URL, adds or removes entries, it also adjusts entries in and out of our gravity DB too? If so, the sync is a replacement. That makes perfect sense! 

2. Yes, I grossly misunderstood the adslist URLs is more like a source list of lists and not the source URLs for domains to block LOL

You built one killer tool! Thanks so much for sharing it!

**Comment by jacklul** [comment]
I could add config option to ignore download failures but it can lead to unwanted behavior.
