### ISSUE TITLE
Where are garbage files collected?

### ISSUE THREAD

**Issue by eh8** [jacklul/pihole-updatelists#29]
I ran `pihole-updatelists` mistakenly and the script began inserting links before I aborted the process. Databases had not yet been swapped. I want to make sure the aborted database is not hogging space on my drive, where can I find and delete it? Thanks.

**Comment by jacklul** [comment]
If you mean the gravity update then it's handled by Pi-hole, it does create some files in /tmp and /etc/pihole/gravity_temp.db (which is deleted next time gravity update runs).

**Comment by eh8** [comment]
Got it, just wanted to make sure it wasn’t hogging disk space. Thanks!
GitHub <notifications@github.com> wrote:
“If you mean the gravity update then it's handled by Pi-hole, it does create some files in /tmp and /etc/pihole/gravity_temp.db (which is deleted next time gravity update runs).”
