### ISSUE TITLE
Pihole -g output

### ISSUE THREAD

**Issue by p1r473** [jacklul/pihole-updatelists#3]
Hi,
The official pihole -g provides some logging such as
-invalid sources
-invalid domains in sources
etc.

Can you we get an output of pihole -g?

**Comment by jacklul** [comment]
What do you mean? This script still runs `pihole -g` at the end.
It only outputs what remote entries were enabled/disabled and possible SQL errors.

**Comment by p1r473** [comment]
Where does it log to? I am running it as a background service (as thats how you set it up)
I checked /var/log/pihole.log but it wasnt updated with the pihole -g output

**Comment by jacklul** [comment]
I mean it sends output to console, you could simply redirect it to file of your choice

**Comment by p1r473** [comment]
Thanks! I'll do that
