### ISSUE TITLE
docker support?

### ISSUE THREAD

**Issue by clyso** [jacklul/pihole-updatelists#30]
is there support for Docker Pi-hole?

**Comment by jacklul** [comment]
I have zero experience with docker, you should be able to install the script and use `GRAVITY_DB` config variable to point the script to the location of the `gravity.db` file (I assume docker saves it somewhere), it will be good idea to also set `UPDATE_GRAVITY=false` to prevent script whining about missing executables.

```bash
sudo nano /etc/pihole-updatelists.conf
```
```
# This has to be done by `docker exec`, override systemd service - see below
UPDATE_GRAVITY=false

# Path to the location of the `gravity.db` file
GRAVITY_DB="/opt/docker/pihole/etc-pihole/gravity.db"
```

```bash
sudo systemctl edit pihole-updatelists.service
```
```
[Service]
Type=oneshot
ExecStartPost=docker exec -it <container_id_or_name> /usr/local/bin/pihole updateGravity
```

**Comment by clyso** [comment]
ok, i will look into it and let you know :-)

**Comment by merc4derp** [comment]
How about throwing the script itself in a container with php-sqlite installed and giving the container access to gravity.db from pihole's container? Would it need access to anything else to do its job?
Would have to not update gravity at all probably this way though and rely exclusively on pihole's default update schedule in its own container. 
See any potential problems with that?

**Comment by merc4derp** [comment]
Should also mention I tried your previous recommendation and ended up with an

Exception: SQLSTATE[HY000] [14] unable to open database file

Path to gravity.db was properly configured and I ran the updatelists command as root. Whatever the issue, its not about file permissions. And that's as far as my php/sql troubleshooting can take me.

**Comment by jacklul** [comment]
> Should also mention I tried your previous recommendation and ended up with an

It was just a guess, the file might be locked by docker or permissions do not allow the file to be opened

**Comment by Dagdelo** [comment]
I mannaged to setup the script on the running container. Just followed the same instructions (installing some necessary programs like nano etc) then after running the script this is the [log](https://pastebin.com/BQAmQtqi) (two runs one with update gravity and one without)

**Comment by jacklul** [comment]
> I managed to set up the script on the running container. Just follow the same instructions (installing some necessary programs like nano etc) then after running the script this is the [log](https://pastebin.com/BQAmQtqi) (two runs one with update gravity and one without)

It's not ideal solution because it will be gone when you update the pi-hole image, the actual solution might be actually having separate container for the script with shared path to the gravity.db and ability to execute command on the other instance

**Comment by Dagdelo** [comment]
We can create another image based on docker/pi-hole and do the set-up, I guess.

**Comment by scantineau** [comment]
Hello !
I forked the project and added a Dockerfile, updated the bash scripts... Working like a charm... 
Proposed a pull request, feel free to accept it or not.
You have to know that the Docker image is available as scantineau/pihole and it will be automatically built when the base image (pihole) will be updated.

**Comment by jacklul** [comment]
[Implemented](https://hub.docker.com/r/jacklul/pihole) in a bit different approach than @scantineau but it seems to be working, anyone up for veryifing and testing this on their end?

**Comment by scantineau** [comment]
I will check but probably not today, maybe tomorrow.
Did you automate Docker build when base image is updated ?

**Comment by jacklul** [comment]
> I will check but probably not today, maybe tomorrow.
> Did you automate Docker build when base image is updated ?

I think so, is this the option?
![](https://i.imgur.com/rCY6U73.png)

**Comment by scantineau** [comment]
Yeah that's it !
It will be multiarch since the "latest" pihole image is multiarch :
![image](https://user-images.githubusercontent.com/8235116/89167280-7cd13300-d57b-11ea-963e-029860e07a16.png)

**Comment by jacklul** [comment]
> Yeah that's it !
> It will be multiarch since the "latest" pihole image is multiarch :
> ![image](https://user-images.githubusercontent.com/8235116/89167280-7cd13300-d57b-11ea-963e-029860e07a16.png)

Yeah but it builds only for amd64, the others are not build? Unless the other archs will be build on the client who pulls the image?

**Comment by scantineau** [comment]
Mmmmh indeed... I don't know why...

**Comment by jacklul** [comment]
From what I see it's not yet supported, multiarch builds must be uploaded manually

**Comment by scantineau** [comment]
Since the full project is provided, he will just have to git clone and docker build

**Comment by scantineau** [comment]
The Docker image is ok :wink:

**Comment by jacklul** [comment]
I figured it out, needed a lot of work and testing but I managed to set it up with the autobuilder. 😊

**Comment by scantineau** [comment]
Yeah ! Can you share ?

**Comment by jacklul** [comment]
> Yeah ! Can you share ?

It's all in the repo, based off https://github.com/rmoriz/multiarch-test with several needed modifications

**Comment by scantineau** [comment]
Sorry, thought it was something to configure directly on docker hub :-)

Thanks and great job !
