### ISSUE TITLE
pihole running on centos?

### ISSUE THREAD

**Issue by ckouris84** [jacklul/pihole-updatelists#31]
what would be necessary to install this on a pi-hole instance running on centos 7?

**Comment by jacklul** [comment]
Did you tried the install script...?

**Comment by ckouris84** [comment]
Yes, I tried the install script.

**Comment by jacklul** [comment]
So what is the issue here? I assume it works fine since you didn't mention any error.

**Comment by ckouris84** [comment]
CentOS seems to have an issue with the binary being picked up in the ENV path variable. I had to export a replacement path variable with the original that I had already, plus adding /usr/local/sbin/, so I can call up the binary without specifying the full path.

**Comment by jacklul** [comment]
I noticed some distros does not add *sbin to the PATH for users with sudo access, only added for root.

This is something I even mentioned in the readme

**Comment by ckouris84** [comment]
It would be good if we could check to the presence of *sbin in the PATH, and if so, take the value of PATH and append the *sbin value, right?

**Comment by jacklul** [comment]
This is something user should do, it's usually ~/.profile, ~/.bashrc or similar file.
