### ISSUE TITLE
Unable to get it working

### ISSUE THREAD

**Issue by Vkad00** [jacklul/pihole-updatelists#33]
I tried to follow the steps to install on raspberry zero w , but the following file is not getting created. 
/etc/cron.d/pihole-updatelists 

I am on the current version of pihole. 

pihole -v
  Pi-hole version is v5.1.1 (Latest: v5.1.1)
  AdminLTE version is v5.1 (Latest: v5.1)
  FTL version is v5.1 (Latest: v5.1)

Raspbian version
Linux raspberrypi 5.4.51+ #1327 Thu Jul 23 10:53:06 BST 2020 armv6l GNU/Linux

**Comment by jacklul** [comment]
Raspbian is using systemd, in this case install script installed timer file, they are more precise than cron and can run missed tasks.

**Comment by Vkad00** [comment]
So following your install steps didnt help do that, any idea how to get that install completed?

wget -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/install.sh | sudo bash

**Comment by jacklul** [comment]
> So following your install steps didnt help do that, any idea how to get that install completed?
> 
> wget -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/install.sh | sudo bash

What error you're getting? Running this command installs everything you need

**Comment by Vkad00** [comment]
It completes but like the issue reported doesnt create the file /etc/cron.d/pihole-updatelists and no cron is created to .

**Comment by jacklul** [comment]
Please re-read my first comment.

Then this part from the readme:
> If systemd is available this will also add service and timer unit files to the system, otherwise a crontab entry in /etc/cron.d/pihole-updatelists will be created.
