### ISSUE TITLE
Error with whitelist/regex - PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed

### ISSUE THREAD

**Issue by earlcray** [jacklul/pihole-updatelists#34]
Hey would appreciate some help with this. 

**Output when running script with -d -v**

SQL Query: SELECT * FROM `domainlist`
Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... done (194 entries)
Processing...
SQL Query: SELECT * FROM `domainlist` WHERE `enabled` = 1 AND `type` = 0 AND `comment` LIKE "%Managed%"
SQL Query: INSERT INTO `domainlist` (domain, type, enabled, comment) VALUES ("0.client-channel.google.com", 0, 1, "Managed")
Inserted: 0.client-channel.google.com
SQL Query: INSERT INTO `domainlist` (domain, type, enabled, comment) VALUES ("1drv.com", 0, 1, "Managed")
Inserted: 1drv.com
SQL Query: INSERT INTO `domainlist` (domain, type, enabled, comment) VALUES ("2.android.pool.ntp.org", 0, 1, "Managed")
Inserted: 2.android.pool.ntp.org
SQL Query: INSERT INTO `domainlist` (domain, type, enabled, comment) VALUES ("akamaihd.net", 0, 1, "Managed")
Inserted: akamaihd.net
SQL Query: INSERT INTO `domainlist` (domain, type, enabled, comment) VALUES ("akamaitechnologies.com", 0, 1, "Managed")
Inserted: akamaitechnologies.com
SQL Query: INSERT INTO `domainlist` (domain, type, enabled, comment) VALUES ("akamaized.net", 0, 1, "Managed")
PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: domainlist_by_group.domainlist_id, domainlist_by_group.group_id in /usr/local/sbin/pihole-updatelists:742
Stack trace:
#0 /usr/local/sbin/pihole-updatelists(742): PDOStatement->execute(NULL)
#1 /usr/local/sbin/pihole-updatelists(1356): LoggedPDOStatement->execute()
#2 {main}
Releasing lock and removing lockfile: /var/lock/pihole-updatelists.lock

**Current config file:**

; Pi-hole's Lists Updater by Jack'lul
; https://github.com/jacklul/pihole-updatelists

; Remote list URL containing list of adlists to import
ADLISTS_URL="https://v.firebog.net/hosts/lists.php?type=tick"

; Remote list URL containing exact domains to whitelist
WHITELIST_URL="https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt"

; Remote list URL containing regex rules for whitelisting
REGEX_WHITELIST_URL=""

; Remote list URL containing exact domains to blacklist
BLACKLIST_URL=""

; Remote list URL containing regex rules for blacklisting
REGEX_BLACKLIST_URL="https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list"

; =============================================================
; OPTIONAL PARAMETERS (and their default values)
; To change them you have to uncomment them first (remove prefixing ';')

; Comment string used to know which entries were created by the script
; You can still add your own comments to individual entries as long
; you keep this string intact
COMMENT="Managed"

; Assign additional group to all inserted entries
; To assign only the specified group make the number negative
; `0` is the default group, you can view ID of the group in Pi-hole's web interface
; by hovering mouse cursor over group name field on the 'Group management' page
;GROUP_ID=0

; Prevent touching entries not created by this script by comparing comment field
; When disabled any user-created entry will be disabled
;REQUIRE_COMMENT=true

; Update gravity after lists are updated? (runs `pihole updateGravity`)
; When disabled invokes lists reload instead
; Set to 'null' to do nothing
UPDATE_GRAVITY=false

; Vacuum database at the end? (runs `VACUUM` SQLite command)
; Will cause additional writes to disk
;VACUUM_DATABASE=false

; Show more information while the script is running
;VERBOSE=false

; Show debug messages
;DEBUG=false

; Maximum time in seconds one list download can take before giving up
; You should increase this when downloads fail because of timeout
;DOWNLOAD_TIMEOUT=60

**Comment by jacklul** [comment]
Have you been running any SQL commands on the database lately? (for example some from the readme?)

**Comment by earlcray** [comment]
yep cleared out existing domains using:
` sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM adlist"
 sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM domainlist"`

**Comment by jacklul** [comment]
Ok, does this produce any output?
sqlite3 /etc/pihole/gravity.db "SELECT * FROM domainlist_by_group"

**Comment by earlcray** [comment]
Output from that is:

pi@pihole:~ $  sudo sqlite3 /etc/pihole/gravity.db "SELECT * FROM domainlist_by_group"
6|0
7|0

**Comment by jacklul** [comment]
Do you have anything on the whitelist/blacklist ?
If they are empty this should fix the issue:
```
sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM domainlist_by_group"
```

**Comment by earlcray** [comment]
Great. Script completed successfully. Thank you! Just so I understand better, what was the issue?

**Comment by jacklul** [comment]
> ` sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM adlist" sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM domainlist"`

Seems like these commands didn't fully clean up the join table ("domainlist_by_group"), I will put info into readme about this so that nobody else gets troubled by this
