### ISSUE TITLE
Updates, releases, notifications

### ISSUE THREAD

**Issue by notDavid** [jacklul/pihole-updatelists#36]
Hi there, you should consider creating [releases](https://github.com/jacklul/pihole-updatelists/releases) once in a while, that way people can set up notifications of updates to your code 🙂 🙏🏼

**Comment by jacklul** [comment]
There is also `pihole-updatelists --version` possibility, this can be put into crontab to send mail or Telegram message directly from the system.
I went with no-versioning approach and only md5 sum is checked to determine if new version is available.

**Comment by notDavid** [comment]
Okay will use that, thanks :)
