### ISSUE TITLE
php doesn't like ipv6

### ISSUE THREAD

**Issue by rmjacobson** [jacklul/pihole-updatelists#37]
If pihole is set to resolve IPv6, the php function `file_get_contents` will automatically attempt to bind to an IPv6 address -- which seems to be broken on Raspbian Buster (and probably earlier).  For reference, the error I get is:
```
SQL Query: SELECT * FROM `adlist`
Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=nocross'... failed to open stream: Connection timed out
```

I looked into this, and found that you can force `file_get_contents` to bind to an IPv4 address by including the following in the `stream_context_create` options array:
```
'socket' => [
    'bindto' => '0:0'
]
```

I've managed to fix this for myself locally, but if you want to future-proof this tool for wider IPv6 use, I recommend either forcing all the bindings to IPv4 like above, or looking into using cURL (which has support for IPv6 builtin, if I understood the docs correctly).

**Comment by jacklul** [comment]
Install `php-curl` package and try development version (`sudo pihole-updatelists --update --git-branch=develop`)
It will use cURL when it's available, otherwise will keep using `file_get_contents()`, `php-curl` is now recommended optional extension.

**Comment by rmjacobson** [comment]
That does seem to solve the problem.  Thanks for addressing this so quickly, I appreciate the attention paid to the project!

**Comment by jacklul** [comment]
I'll merge it right away.

_Also `--git-branch=develop` overrides config, added this specifically for this type of situations._
