### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by blaze8218** [jacklul/pihole-updatelists#38]
I installed per directions. And cannot get it to update or install.
I had used yours in the past with the install.sh but it states no such file or directory.
I did do a git clone "website" and then tried the install.sh and nada.

Ill admit the previous way was lot easier and dont really understand what im doing in terms of what its installing or how the script is ran i just punch commands and hope it works.

sudo apt-get install php-cli php-pdo php-pdo-sqlite php-sqlit                                                                                                                                                             e3 php-intl php-curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php-pdo is a virtual package provided by:
  php7.3-common 7.3.19-1~deb10u1
  php7.2-common 7.2.9-1+b2
  php7.1-common 7.1.20-1+b2
You should explicitly select one to install.

Package php-pdo-sqlite is a virtual package provided by:
  php7.3-sqlite3 7.3.19-1~deb10u1
  php7.2-sqlite3 7.2.9-1+b2
  php7.1-sqlite3 7.1.20-1+b2
You should explicitly select one to install.

E: Package 'php-pdo' has no installation candidate
E: Package 'php-pdo-sqlite' has no installation candidate

wget -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/install.sh | sudo bash
--2020-08-18 19:08:14--  https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.192.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5667 (5.5K) [text/plain]
Saving to: ‘STDOUT’

-                                                           100%[========================================================================================================================================>]   5.53K  --.-KB/s    in 0s

2020-08-18 19:08:14 (12.7 MB/s) - written to stdout [5667/5667]

2020-08-18 19:08:15 URL:https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/pihole-updatelists.php [64316/64316] -> "/usr/local/sbin/pihole-updatelists" [1]
mode of '/usr/local/sbin/pihole-updatelists' retained as 0755 (rwxr-xr-x)
2020-08-18 19:08:15 URL:https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/pihole-updatelists.service [229/229] -> "/etc/systemd/system/pihole-updatelists.service" [1]
2020-08-18 19:08:15 URL:https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/pihole-updatelists.timer [164/164] -> "/etc/systemd/system/pihole-updatelists.timer" [1]
2020-08-18 19:08:16 URL:https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/pihole-updatelists.bash [1147/1147] -> "/etc/bash_completion.d/pihole-updatelists" [1]
Reloading systemd manager configuration...
pi@raspberrypi:~ $ pihole-updatelists -d
Acquired process lock through file: /var/lock/pihole-updatelists.lock

      Pi-hole's Lists Updater by Jack'lul
 https://github.com/jacklul/pihole-updatelists

Missing recommended PHP extension: php-curl
You can install missing extensions using `apt-get install php-curl`

Checksum: 5d6f36379a54a7866eed866b1518359f
Git branch: master
OS: Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l
PHP: 7.3.19-1~deb10u1 NTS
SQLite: 3.27.2
cURL: Unavailable
Pi-hole Core: v5.1.2-0-g6b536b7 (master)
Pi-hole Web: v5.1.1-0-ga03d1bd (master)
Pi-hole FTL: v5.2 (master)
Configuration: array(19) {
  ["CONFIG_FILE"] => string(28) "/etc/pihole-updatelists.conf"
  ["GRAVITY_DB"] => string(22) "/etc/pihole/gravity.db"
  ["LOCK_FILE"] => string(33) "/var/lock/pihole-updatelists.lock"
  ["LOG_FILE"] => string(0) ""
  ["ADLISTS_URL"] => string(0) ""
  ["WHITELIST_URL"] => string(0) ""
  ["REGEX_WHITELIST_URL"] => string(0) ""
  ["BLACKLIST_URL"] => string(0) ""
  ["REGEX_BLACKLIST_URL"] => string(0) ""
  ["COMMENT"] => string(29) "Managed by pihole-updatelists"
  ["GROUP_ID"] => int(0)
  ["REQUIRE_COMMENT"] => bool(true)
  ["UPDATE_GRAVITY"] => bool(true)
  ["VACUUM_DATABASE"] => bool(false)
  ["VERBOSE"] => bool(false)
  ["DEBUG"] => bool(true)
  ["DOWNLOAD_TIMEOUT"] => int(60)
  ["IGNORE_DOWNLOAD_FAILURE"] => bool(false)
  ["GIT_BRANCH"] => string(6) "master"
}
Options: array(1) {
  ["debug"] => bool(false)
}

Opened gravity database: /etc/pihole/gravity.db (4.88 MB)

SQL Query: SELECT `id` FROM `adlist` WHERE `comment` LIKE "%Managed by pihole-updatelists%" AND `enabled` = 1 LIMIT 1
SQL Query: SELECT * FROM `domainlist`
SQL Query: SELECT id FROM `domainlist` WHERE `comment` LIKE "%Managed by pihole-updatelists%" AND `enabled` = 1 AND `type` = 0 LIMIT 1
SQL Query: SELECT id FROM `domainlist` WHERE `comment` LIKE "%Managed by pihole-updatelists%" AND `enabled` = 1 AND `type` = 2 LIMIT 1
SQL Query: SELECT id FROM `domainlist` WHERE `comment` LIKE "%Managed by pihole-updatelists%" AND `enabled` = 1 AND `type` = 1 LIMIT 1
SQL Query: SELECT id FROM `domainlist` WHERE `comment` LIKE "%Managed by pihole-updatelists%" AND `enabled` = 1 AND `type` = 3 LIMIT 1
Closed database handles.
Updating Pi-hole's gravity...
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Received 58488 domains

  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [✓] Status: No changes detected
  [i] Received 26854 domains

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 85342 (85298 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Cleaning up stray matter

  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled

Memory reached peak usage of 859.17 KB
Finished successfully with 1 warning(s) in 3.52 seconds.
Releasing lock and removing lockfile: /var/lock/pihole-updatelists.lock

**Comment by jacklul** [comment]
> sudo apt-get install php-cli php-pdo php-pdo-sqlite php-sqlit e3 php-intl php-curl
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Package php-pdo is a virtual package provided by:
> php7.3-common 7.3.19-1~deb10u1
> php7.2-common 7.2.9-1+b2
> php7.1-common 7.1.20-1+b2
> You should explicitly select one to install.
> 
> Package php-pdo-sqlite is a virtual package provided by:
> php7.3-sqlite3 7.3.19-1~deb10u1
> php7.2-sqlite3 7.2.9-1+b2
> php7.1-sqlite3 7.1.20-1+b2
> You should explicitly select one to install.
> 
> E: Package 'php-pdo' has no installation candidate
> E: Package 'php-pdo-sqlite' has no installation candidate

You just do what it says - `sudo apt-get install php-cli php-common php-sqlite3 php-intl php-curl`
I'll update readme

**Comment by blaze8218** [comment]
pi@raspberrypi:~ $ sudo apt-get install php7.3-interbase
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  rpi-eeprom-images
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  php7.3-interbase
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 34.7 kB of archives.
After this operation, 125 kB of additional disk space will be used.
Get:1 http://mirrors.gigenet.com/raspbian/raspbian buster/main armhf php7.3-inte                              rbase armhf 7.3.19-1~deb10u1 [34.7 kB]
Fetched 34.7 kB in 1s (57.4 kB/s)
Selecting previously unselected package php7.3-interbase.
(Reading database ... 156535 files and directories currently installed.)
Preparing to unpack .../php7.3-interbase_7.3.19-1~deb10u1_armhf.deb ...
Unpacking php7.3-interbase (7.3.19-1~deb10u1) ...
Setting up php7.3-interbase (7.3.19-1~deb10u1) ...

Creating config file /etc/php/7.3/mods-available/interbase.ini with new version

Creating config file /etc/php/7.3/mods-available/pdo_firebird.ini with new versi                              on
pi@raspberrypi:~ $ sudo apt-get install php7.3-common
Reading package lists... Done
Building dependency tree
Reading state information... Done
php7.3-common is already the newest version (7.3.19-1~deb10u1).
php7.3-common set to manually installed.
The following package was automatically installed and is no longer required:
  rpi-eeprom-images
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

pi@raspberrypi:~ $ sudo apt-get install php-cli php-sqlite3 php-intl php-curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
php-intl is already the newest version (2:7.3+69).
php-sqlite3 is already the newest version (2:7.3+69).
The following package was automatically installed and is no longer required:
  rpi-eeprom-images
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  php7.3-curl
The following NEW packages will be installed:
  php-cli php-curl php7.3-curl
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 38.8 kB of archives.
After this operation, 138 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:2 http://mirrors.gigenet.com/raspbian/raspbian buster/main armhf php7.3-curl                               armhf 7.3.19-1~deb10u1 [26.7 kB]
Get:1 http://mirror.sjc02.svwh.net/raspbian/raspbian buster/main armhf php-cli a                              ll 2:7.3+69 [6,052 B]
Get:3 http://mirror.sjc02.svwh.net/raspbian/raspbian buster/main armhf php-curl                               all 2:7.3+69 [5,992 B]
Fetched 38.8 kB in 1s (28.1 kB/s)
Selecting previously unselected package php-cli.
(Reading database ... 156546 files and directories currently installed.)
Preparing to unpack .../php-cli_2%3a7.3+69_all.deb ...
Unpacking php-cli (2:7.3+69) ...
Selecting previously unselected package php7.3-curl.
Preparing to unpack .../php7.3-curl_7.3.19-1~deb10u1_armhf.deb ...
Unpacking php7.3-curl (7.3.19-1~deb10u1) ...
Selecting previously unselected package php-curl.
Preparing to unpack .../php-curl_2%3a7.3+69_all.deb ...
Unpacking php-curl (2:7.3+69) ...
Setting up php-cli (2:7.3+69) ...
Setting up php7.3-curl (7.3.19-1~deb10u1) ...

Creating config file /etc/php/7.3/mods-available/curl.ini with new version
Setting up php-curl (2:7.3+69) ...
pi@raspberrypi:~ $ wget -O - https://raw.githubusercontent.com/jacklul/pihole-up                              datelists/master/install.sh | sudo bash
--2020-08-19 07:42:39--  https://raw.githubusercontent.com/jacklul/pihole-update                              lists/master/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.1                              33, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.                              133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5667 (5.5K) [text/plain]
Saving to: ‘STDOUT’

-                   100%[===================>]   5.53K  --.-KB/s    in 0s

2020-08-19 07:42:39 (13.3 MB/s) - written to stdout [5667/5667]

2020-08-19 07:42:39 URL:https://raw.githubusercontent.com/jacklul/pihole-updatel                              ists/master/pihole-updatelists.php [64316/64316] -> "/usr/local/sbin/pihole-upda                              telists" [1]
mode of '/usr/local/sbin/pihole-updatelists' retained as 0755 (rwxr-xr-x)
2020-08-19 07:42:40 URL:https://raw.githubusercontent.com/jacklul/pihole-updatel                              ists/master/pihole-updatelists.service [229/229] -> "/etc/systemd/system/pihole-                              updatelists.service" [1]
2020-08-19 07:42:40 URL:https://raw.githubusercontent.com/jacklul/pihole-updatel                              ists/master/pihole-updatelists.timer [164/164] -> "/etc/systemd/system/pihole-up                              datelists.timer" [1]
2020-08-19 07:42:40 URL:https://raw.githubusercontent.com/jacklul/pihole-updatel                              ists/master/pihole-updatelists.bash [1147/1147] -> "/etc/bash_completion.d/pihol                              e-updatelists" [1]
Reloading systemd manager configuration...


pi@raspberrypi:~ $ pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Received 58488 domains

  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [✓] Status: No changes detected
  [i] Received 26854 domains

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [i] Number of gravity domains: 85342 (85298 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [✓] Flushing DNS cache
  [✓] Cleaning up stray matter

  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled

**Comment by jacklul** [comment]
I can't see a problem here, everything works?
