### ISSUE TITLE
Configuration of pihole-updatelists for multiple groups 

### ISSUE THREAD

**Issue by schokiss09** [jacklul/pihole-updatelists#39]
Hello! 

I'm running Pi-hole on a Raspberry 4. The adlists are being update once a week and all lists are assigned to the default group.
Now that I use two additional user groups (ID=4, ID=6) I want all lists to be assigned to these user groups as well. I tried the following parameter in the conf-file:
...
; Assign additional group to all inserted entries
; To assign only specified group make the number negative
; `0` is the default group, you can view ID of the group in Pi-hole's web interface
; by hovering mouse cursor over group name field on the 'Group management' page
GROUP_ID=0
GROUP_ID=4
GROUP_ID=6
...
When I run pihole-updatelists after saving the conf-file, all lists are being updated but still they are only assigned to my default group. What am I doing wrong?

Thank you very much in advance for your support. I'm doing my best to make things work.

**Comment by jacklul** [comment]
You can currently only have all entries assigned to either:
- default group and your selected group (positive non-zero number)
- only your group (negative number)

It doesn't make sense to have two groups with the same lists as you can assign multiple groups to clients.

**Comment by jacklul** [comment]
@schokiss09 closing this one off due to inactivity.
