### ISSUE TITLE
1gb gravity.db due to duplicates?

### ISSUE THREAD

**Issue by p1r473** [jacklul/pihole-updatelists#4]
Hello,
After running this, the size of gravity.db is 1gb

Looks like there are duplicates. I am viewing the .db file in a SQLite browser and I have 16 million hosts- this is equivalent to how many unique hosts I have. I only have 3 million unique hosts so it looks like duplicates aren't removed.

**Comment by p1r473** [comment]
Here is a screenshot showing duplicates are added

![image](https://user-images.githubusercontent.com/9235633/79702306-e7cb5800-8271-11ea-9267-5da7d71dbdcb.png)

**Comment by p1r473** [comment]
This could be an issue on Pihole's end. I have opened issue # there. If it can be resolved on there end, I will close this issue here.
https://github.com/pi-hole/pi-hole/issues/3286

**Comment by jacklul** [comment]
My script doesn't touch that table which makes it weird

**Comment by p1r473** [comment]
Okay, it might be an issue with PiHole backend then. I'll report back if they can't fix it

**Comment by jacklul** [comment]
This can potentially be caused by their group feature

**Comment by p1r473** [comment]
This is intended functionality apparently of PiHole.
I don't agree with the decision so I am going to try and figure out how to delete duplicates myself out of the database
https://github.com/pi-hole/pi-hole/issues/3286

**Comment by p1r473** [comment]
@jacklul we can run this command to remove duplicates
sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM gravity WHERE rowid NOT IN (SELECT rowid FROM gravity GROUP BY domain); VACUUM;"

Do you want to incorporate this into this project? If not, I can run it in a cronjob on my Pi

**Comment by jacklul** [comment]
> @jacklul we can run this command to remove duplicates
> 
> ```
> sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM gravity WHERE rowid NOT IN (SELECT rowid FROM gravity GROUP BY domain); VACUUM;"
> ```
> 
> Do you want to incorporate this into this project? If not, I can run it in a cronjob on my Pi

I don't want to implement something that isn't supported by Pi-hole and can potentialy break things

**Comment by p1r473** [comment]
Ok thanks! Will run it on my own

**Comment by jacklul** [comment]
> Ok thanks! Will run it on my own

You can override systemd unit file for my script and another thing to run inside it.
`systemctl edit pihole-updatelists.service`

```
[Service]
ExecStartPost=sqlite3 /etc/pihole/gravity.db "DELETE FROM gravity WHERE rowid NOT IN (SELECT rowid FROM gravity GROUP BY domain); VACUUM;"
```

This will run directly after `systemctl start pihole-updatelists.service` (or schedule), will not run when executed by `pihole-updatelists`!

**Comment by p1r473** [comment]
Thanks, this is way better than a cronjob.
I used this, as I have some stuff before, and some stuff after I want to do.

[Service]
Type=simple
ExecStartPre=/home/linaro/hostserv-pre.sh
ExecStart=/usr/local/sbin/pihole-updatelists
ExecStartPost=/home/linaro/hostserv-pre.sh

**Comment by jacklul** [comment]
> Thanks for telling me about this, this is way better than a cronjob!!!
> I used this, as I have some stuff before, and some stuff after I want to do.
> 
> [Service]
> Type=simple
> ExecStartPre=/home/linaro/hostserv-pre.sh
> ExecStart=/usr/local/sbin/pihole-updatelists
> ExecStartPost=/home/linaro/hostserv-pre.sh

If you're overriding through `sudo systemctl edit pihole-updatelists.service` there is no need for these:
```
Type=simple
ExecStart=/usr/local/sbin/pihole-updatelists
```

**Comment by p1r473** [comment]
Sorry, I dont follow, what do you mean?
I had added those lines into the .service from your Git, and then ran .install, so now
```
cat /etc/systemd/system/pihole-updatelists.service
[Unit]
Description=Update Pi-hole's lists from remote sources
After=network-online.target multi-user.target
Wants=network-online.target

[Service]
Type=simple
ExecStartPre=/home/linaro/hostserv-pre.sh
ExecStart=/usr/local/sbin/pihole-updatelists
ExecStartPost=/home/linaro/hostserv-pre.sh
```

**Comment by jacklul** [comment]
You're doing it wrong, you should not do this, instead run `sudo systemctl edit pihole-updatelists.service` and in the editor you paste what you want to add/change.
it will create `/etc/systemd/system/pihole-updatelists.service.d/override.conf`.

**Comment by p1r473** [comment]
So I paste the entire modified .service into the override?

**Comment by p1r473** [comment]
> > Thanks for telling me about this, this is way better than a cronjob!!!
> > I used this, as I have some stuff before, and some stuff after I want to do.
> > [Service]
> > Type=simple
> > ExecStartPre=/home/linaro/hostserv-pre.sh
> > ExecStart=/usr/local/sbin/pihole-updatelists
> > ExecStartPost=/home/linaro/hostserv-pre.sh
> 
> If you're overriding through `sudo systemctl edit pihole-updatelists.service` there is no need for these:
> 
> ```
> Type=simple
> ExecStart=/usr/local/sbin/pihole-updatelists
> ```
> 
> Both files are combined into one, override takes priority

So what do I paste in the override file then, this? The whole thing, or just parts of it? Is any of the non-overidden part kept?


```
[Unit]
Description=Update Pi-hole's lists from remote sources
After=network-online.target multi-user.target
Wants=network-online.target

[Service]
Type=simple
ExecStartPre=/home/linaro/hostserv-pre.sh
ExecStart=/usr/local/sbin/pihole-updatelists
ExecStartPost=/home/linaro/hostserv-pre.sh
```

**Comment by jacklul** [comment]
- You execute `sudo systemctl edit pihole-updatelists.service`, this will open in-console editor
- You paste:
```bash
[Service]
ExecStartPre=/home/linaro/hostserv-pre.sh
ExecStartPost=/home/linaro/hostserv-pre.sh
```
- You save and quit
- Done

You gotta do this through systemctl so that the unit file is automatically merged after you edit it, manually editing override.conf doesn't do that.

**Comment by p1r473** [comment]
Thanks, learned something new!
Is there no way to back up this change so that in a reformat, I could just paste this file back?
One thing I do is back up all my modified files, so if I ever reformat, instead of configuring, I just paste all the files back in, as everything is just a file in Linux

So if I back up ```/etc/systemd/system/pihole-updatelists.service.d/override.conf``` and restore this file, the changes arent merged automatically?

**Comment by p1r473** [comment]
I imagine I can override the timer in the same way?
```
sudo systemctl edit pihole-updatelists.timer
```
```
[Timer]
OnCalendar=Sat *-*-* 03:00:00
```

**Comment by p1r473** [comment]
> Thanks, learned something new!
> I usually back up all my modified files manually, so in case of a reformat I just paste all the files back in manually to reconfigure most things.
> 
> So if I back up `/etc/systemd/system/pihole-updatelists.service.d/override.conf` and restore this file manually, the changes arent merged automatically, it won't work?

https://docs.varnish-software.com/tutorials/configuring-systemd-services/#manual-changes-to-unit-configuration

It says that "Editing of the systemd units does not require using the interactive command line tools. Identical results can be achieved with dropping override files and or replacement unit files into the relevant systemd directories on your system."

So it looks like if I back up ```/etc/systemd/system/pihole-updatelists.service.d/override.conf``` and restore it later, without using CLI, I should be okay?

**Comment by p1r473** [comment]
> * You execute `sudo systemctl edit pihole-updatelists.service`, this will open in-console editor
> * You paste:
> 
> ```shell
> [Service]
> ExecStartPre=/home/linaro/hostserv-pre.sh
> ExecStartPost=/home/linaro/hostserv-pre.sh
> ```
> 
> * You save and quit
> * Done
> 
> You gotta do this through systemctl so that the unit file is automatically merged after you edit it, manually editing override.conf doesn't do that.

https://docs.varnish-software.com/tutorials/configuring-systemd-services/#manual-changes-to-unit-configuration

It says that "Editing of the systemd units does not require using the interactive command line tools. Identical results can be achieved with dropping override files and or replacement unit files into the relevant systemd directories on your system."

So it looks like if I back up ```/etc/systemd/system/pihole-updatelists.service.d/override.conf``` and restore it later, without using CLI, I should be okay actually actually?

**Comment by jacklul** [comment]
I've been always told those overrides aren't applied until `systemctl daemon-reload` is executed, which happens after you close editor automatically.

**Comment by p1r473** [comment]
So I can drop the override files in, and then run systemctl daemon-reload then?
This will make it easier to back up my overrides instead of manually configure (in case of a reformat I try to back up all the files so I dont need to reconfigure everything)

Did I do the timer right?

**Comment by p1r473** [comment]
> systemctl daemon-reload

Yea
https://coreos.com/os/docs/latest/using-systemd-drop-in-units.html
Looks like as long as I restart the service itll work:
```
You can create a drop-in file /etc/systemd/system/locksmithd.service.d/10-restart_60s.conf with the following contents:

[Service]
RestartSec=60s
Then reload systemd, scanning for new or changed units:

systemctl daemon-reload

And restart modified service if necessary (in our example we have changed only RestartSec option, but if you want to change environment variables, ExecStart or other run options you have to restart service):

systemctl restart locksmithd.service
```

**Comment by p1r473** [comment]
Ill test it manually and post back
Ill set it to trigger in 2 minutes and then Ill see if it works

**Comment by p1r473** [comment]
To anyone else who may have this issue:
The trick was to overwrite with
```
Type=oneshot
```
Instead of the original
```
Type=simple
```

From https://www.freedesktop.org/software/systemd/man/systemd.service.html : 
```
Type= (i.e. the process has been started for Type=simple or Type=idle, **the last ExecStart= process exited successfully for Type=oneshot**, the initial process exited successfully for Type=forking, "READY=1" is sent for Type=notify, or the BusName= has been taken for Type=dbus).
```
