### ISSUE TITLE
Question: Is in possible to assign different groups to different Addlist URLs?

### ISSUE THREAD

**Issue by smokemyshoes** [jacklul/pihole-updatelists#40]
Hi, nice script you have created...

I would like to use your script to pull in two different lists of lists with your script but assign them to different groups, is that possible?

In more details I would like to first pull in "Firebogs ticked lists" and assign them to the default group which my the whole group are in and then pull in "Firebogs non-crossed lists" and assign it to a "strict" group which only I am in. Is that possible

When I to it manually I just import all the ticked lists first, with default group and and afterwards I import the non-crossed lists with the strict group and pi-hole is smart enough to not overwrite the group of the lists that was just pulled in with the ticked lists.

1) Does your script also respect (meaning not overwrite) group of first lists that was imported if they are also in the second list?
2) is in possible in the config-file to specify one group to used for the ticked list and another to be used for the non-crossed list?

TIA

**Comment by jacklul** [comment]
1. Groups are assigned only when new entry is added, after that they are not touched
2. You can use `--config=/etc/pihole-updatelists2.conf` option ([read here](https://github.com/jacklul/pihole-updatelists#runtime-options)) to run the script with different config, then just [override systemd service](https://github.com/jacklul/pihole-updatelists#running-custom-commands-beforeafter-scheduled-run) to add second instance to the schedule

**Comment by smokemyshoes** [comment]
Great, thanks. 

Would you be so kind to spell out the part about overriding systemd service. I’ve never fiddled with systemd and I’m not sure about what you mean by overriding the service

**Comment by jacklul** [comment]
`sudo systemctl edit pihole-updatelists.service`
```bash
[Service]
Type=oneshot
ExecStartPost=/usr/local/sbin/pihole-updatelists --config=/etc/pihole-updatelists2.conf
ExecStartPost=/usr/local/bin/pihole updateGravity
```

Both config files should have `UPDATE_GRAVITY=null` as there is no reason to run it multiple times, just at the end.
This will only affect scheduled run, to have this run manually from the console you will have to `sudo systemctl start pihole-updatelists.service --no-block`.

**Comment by smokemyshoes** [comment]
Great, thanks a lot, I’ll give it a try. 

I am in the default group.
