### ISSUE TITLE
pihole-updatelists is not created during install

### ISSUE THREAD

**Issue by Gil80** [jacklul/pihole-updatelists#41]
Running on RPi 3 B+
I have **systemd** and everything is up to date.
After running this command: `wget -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/install.sh | sudo bash`
I checked **/etc/cron.d/**
![2020-10-12 21_43_01-Window](https://user-images.githubusercontent.com/8454919/95737790-f308b900-0cd3-11eb-995e-5930ada8ef27.png)

**Comment by jacklul** [comment]
That's correct behaviour, if systemd is available a timer will be used instead of cron (they are more reliable).
Cron entry is only installed when for some reason systemd is not available (or is docker install).
