### ISSUE TITLE
Processing time for large blacklist

### ISSUE THREAD

**Issue by pull-q** [jacklul/pihole-updatelists#42]
Hi jacklul,

I've recently installed pihole-updatelists and was running a config with the following:

Remote list URL containing exact domains to blacklist
`BLACKLIST_URL="https://raw.githubusercontent.com/chadmayfield/pihole-blocklists/master/lists/pi_blocklist_porn_all.list"`

First this was killed due to running out o memory, after adding 2GB of swap I could keep it running, however the process was running for 24h and did not finish (after the merging lists" regarding the BLACKLIST_URL. 

Granted, this contains a lot of entries, I am just wondering - should this be added to the script in the first place Or just manually add it to group management?

Thanks in advance and thanks for the great script!

**Comment by jacklul** [comment]
That file is a blocklist, it must be added to the Pi-hole directly (through the web interface).
BLACKLIST_URL is specifically for people who keep their personal blacklisted sites somewhere in the file (or sync with multiple pi's).

**Comment by pull-q** [comment]
hi jacklul!
thanks for the quick response, that explains it (obviously). Maybe I might suggest adding this into the config comments (like "for local handcrafted blacklists only" or something like that – then again, maybe I was the only one misusing/misunderstanding it...)

thanks again!
