### ISSUE TITLE
running pihole-updatelists disabled lists with "Managed by pihole-updatelists" comment

### ISSUE THREAD

**Issue by Gil80** [jacklul/pihole-updatelists#43]
I thought that running `pihole-updateslists` will update all the lists I have in Adlist group management and then do `pihole -g`.
But instead, it disabled all the lists I had with the comment "managed by pihole-updatelists"

```
pi@raspberry:~ $ pihole-updatelists

 Pi-hole's Lists Updater by Jack'lul

 https://github.com/jacklul/pihole-updatelists

Opened gravity database: /etc/pihole/gravity.db (63.81 MB)

No remote list set for ADLISTS, disabling orphaned entries in the database... done (33)

Updating Pi-hole's gravity...
```

What did I do wrong?

**Comment by jacklul** [comment]
Please look into readme, you need some variables to be set for this script to function.
https://github.com/jacklul/pihole-updatelists#available-variables
https://github.com/jacklul/pihole-updatelists#recommended-lists

**Comment by Gil80** [comment]
I read the entire readme several times.
It is not clear what extra steps I need to do other than what is mentioned in the readme.
I re-installed pihole and imported my Adlists, blacklists and whitelists. All I want is the option to update them automatically. I followed every step of the readme and it's not clear to me why it disables adlists with the comment "managed by pihole-updatelists"

**Comment by jacklul** [comment]
You don't need this script for just updating them, Pi-hole handles it by itself.
The purpose of this script is to stay up to date with community lists like https://v.firebog.net/hosts/lists.php?type=tick (`ADLIST_URL`)

**Comment by Gil80** [comment]
So you mean that in **updatelists.conf** file I need to have if configured like this?
`ADLISTS_URL="https://v.firebog.net/hosts/lists.php?type=tick"`

And for:
`WHITELIST_URL="https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt"` ?

If the above is correct (assuming I finally got it), then:
1. I don't need to install anudeepND script because your script will automatically check for updates
2. If a community list is removed, then your script will disable it in pihole
3. All Adlists/Whitelists I have must include "Managed by pihole-updatelists" in double-quotes?
4. Lists that don't have "Managed by pihole-updatelists" will not be touched by your script?

**Comment by jacklul** [comment]
1. You don't need it, it does the same thing
2. Correct
3. No, that comment field is specifically for entries (domains, adlists) coming from the remote lists, you should not set this comment for your personal/custom entries as the script will keep disabling them, double quotes are not needed (it's just indicator in the readme that it's a string type value)
4. Correct, all your custom entries will be left intact

**Comment by Gil80** [comment]
Thank you very much for explaining this to me. Sorry for taking your time. I'm simply new to this.
I assume that my above assumptions are correct then?

I'm just not sure I totally get it. I'm a new learner to linux, networking and pihole. Thank you once again! This seems to be just what I need to make it a bit easier.

**Comment by jacklul** [comment]
1, 2 and 4 points are correct, 3 is not

**Comment by Gil80** [comment]
:) I meant this:
ADLISTS_URL="https://v.firebog.net/hosts/lists.php?type=tick"
And for:
WHITELIST_URL="https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt" ?

Thanks.

**Comment by jacklul** [comment]
> :) I meant this:
> ADLISTS_URL="https://v.firebog.net/hosts/lists.php?type=tick"
> And for:
> WHITELIST_URL="https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt" ?
> 
> Thanks.

Yes, these should go into double quotes
