### ISSUE TITLE
Adlists...processing takes forever

### ISSUE THREAD

**Issue by hyber-code** [jacklul/pihole-updatelists#44]
I added three adlists urls to config. thru ```pihole -g``` with the same urls would usually take a minute or less, however the script is stuck on processing forever.

the result is same on ```google cloud instance``` ```oracle cloud instance``` and ```rasp pi 3b +```

![image](https://user-images.githubusercontent.com/18413990/96371915-a6165e00-117d-11eb-8e38-45bb9d7424c5.png)

**Comment by hyber-code** [comment]
i ended up uninstalling the script and back to adding lists to pi-hole web interface.

**Comment by jacklul** [comment]
You didn't read the readme carefully, `ADLIST_URL` must point to list like this https://v.firebog.net/hosts/lists.php?type=tick

**Comment by hyber-code** [comment]
thank you for your hard work and your response.
my bad, i am trying again by pasting pastebin.com's raw list. i will update here.

**Comment by hyber-code** [comment]
Beautiful...it worked!!
![image](https://user-images.githubusercontent.com/18413990/96372688-6cdfed00-1181-11eb-8786-7314f7d8fd93.png)

Thankyou again for the script.

Stay Blessed
