### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by eyeteajay** [jacklul/pihole-updatelists#46]
Hello,
After recently updating, when I run `pihole-updatelists` on the cmd line, I'm getting this error:
`Exception: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: domainlist.domain, domainlist.type` Please see the attached verbose output.

Is this because I have whitelisted some of the URLs in the gui?

I am using version:
```
Git branch: master
Local checksum: 2f8d11fe7a830821eca6197691fe0763
Remote checksum: 2f8d11fe7a830821eca6197691fe0763
```
[output.txt](https://github.com/jacklul/pihole-updatelists/files/5461936/output.txt)
Thanks

**Comment by eyeteajay** [comment]
I've also included my config, pretty much all vanilla
[pihole-updatelists.conf.txt](https://github.com/jacklul/pihole-updatelists/files/5461971/pihole-updatelists.conf.txt)

**Comment by jacklul** [comment]
Running with debug mode would help more than just verbose mode, also you don't need to include `type=tick` list as `type=nocross` list already includes same entries

**Comment by hardcoregandhi** [comment]
#34 Try the command posted here, https://github.com/jacklul/pihole-updatelists/issues/34#issuecomment-665619077
`sudo sqlite3 /etc/pihole/gravity.db "DELETE FROM domainlist_by_group"`

**Comment by jacklul** [comment]
Closed due to inactivity
