### ISSUE TITLE
No crontab or systemd timer after install?

### ISSUE THREAD

**Issue by spm2600** [jacklul/pihole-updatelists#47]
Ran through steps, added recommended lists.  Went to check timer and see no service for pihole-updatelists.

Per requirements I ran "sudo apt-get install php-cli php-sqlite3 php-intl php-curl" and checked that systemd was already installed.

below is empty
sudo systemctl edit pihole-updatelists.timer

was not created
/etc/cron.d/pihole-updatelists

I ran "pihole-updatelists" succesfully and see on my dashboard the increase in sites.  Would like to ensure this runs on schedule, I did not have any problems with install so wondering why those weren't added.

**Comment by jacklul** [comment]
`sudo systemctl edit pihole-updatelists.timer` edits override file (which by default is empty)
Use `systemctl list-timers` to verify that the timer exists.

**Comment by spm2600** [comment]
Bingo!  Thanks, learning Linux as I go.
