### ISSUE TITLE
CHeck if it does work?

### ISSUE THREAD

**Issue by StifflersMoM69** [jacklul/pihole-updatelists#48]
How can i check if the script works and the lists are getting updated?
When running the script, statusin Adlist group management turns into "Disabled".
Is this normal?

**Comment by jacklul** [comment]
> How can i check if the script works and the lists are getting updated?
> When running the script, statusin Adlist group management turns into "Disabled".
> Is this normal?

It shouldn't that if it's properly configured.
Please run `pihole-updatelists -d --version` and show me the output.

You can run the script in verbose mode to see what's happening `pihole-updatelists -v`.

**Comment by StifflersMoM69** [comment]
Thanks for getting back in touch with me. Here is the output.
`Checksum: 2f8d11fe7a830821eca6197691fe0763
Git branch: master
OS: Linux raspberrypi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l
PHP: 7.3.19-1~deb10u1 NTS
SQLite: 3.27.2
cURL: 7.64.0
Pi-hole Core: v5.2-0-gfee1b8b (master)
Pi-hole Web: v5.2-0-g2c2d9f5 (master)
Pi-hole FTL: v5.3.1 (master)
Configuration: array(20) {
  ["CONFIG_FILE"] => string(28) "/etc/pihole-updatelists.conf"
  ["GRAVITY_DB"] => string(22) "/etc/pihole/gravity.db"
  ["LOCK_FILE"] => string(33) "/var/lock/pihole-updatelists.lock"
  ["LOG_FILE"] => string(0) ""
  ["ADLISTS_URL"] => string(0) ""
  ["WHITELIST_URL"] => string(0) ""
  ["REGEX_WHITELIST_URL"] => string(0) ""
  ["BLACKLIST_URL"] => string(0) ""
  ["REGEX_BLACKLIST_URL"] => string(0) ""
  ["COMMENT"] => string(29) "Managed by pihole-updatelists"
  ["GROUP_ID"] => int(0)
  ["PERSISTENT_GROUP"] => bool(false)
  ["REQUIRE_COMMENT"] => bool(true)
  ["UPDATE_GRAVITY"] => bool(true)
  ["VACUUM_DATABASE"] => bool(false)
  ["VERBOSE"] => bool(false)
  ["DEBUG"] => bool(true)
  ["DOWNLOAD_TIMEOUT"] => int(60)
  ["IGNORE_DOWNLOAD_FAILURE"] => bool(false)
  ["GIT_BRANCH"] => string(6) "master"
}
Options: array(2) {
  ["version"] => bool(false)
  ["debug"] => bool(false)
}

Git branch: master
Local checksum: 2f8d11fe7a830821eca6197691fe0763
Remote checksum: 2f8d11fe7a830821eca6197691fe0763
The script is up to date!`

**Comment by jacklul** [comment]
You have no `_URL` variable set, this makes this script useless, don't tell me you just replaced comments with "Managed by pihole-updatelists" and assumed it will do any magic?
It's purpose is to pull lists like [this](https://v.firebog.net/hosts/lists.php?type=tick) or [this](https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt) weekly and update records in your Pi-hole installation.

**Comment by StifflersMoM69** [comment]
Hi. Yes thats exactly what i did. Like described. I Cant see what i missed out.
```
Alternatively, some manual work is required - pick one:

    Manually modify comment field of all imported domains/adlists to match the one this script uses (see COMMENT variable in Configuration section) (recommended but might be a lot of work)
```

**Comment by jacklul** [comment]
> Hi. Yes thats exactly what i did. Like described. I Cant see what i missed out.
> 
> ```
> Alternatively, some manual work is required - pick one:
> 
>     Manually modify comment field of all imported domains/adlists to match the one this script uses (see COMMENT variable in Configuration section) (recommended but might be a lot of work)
> ```

**You have no *_URL variable set, this makes this script useless.**

**Comment by StifflersMoM69** [comment]
Guess i understood. I have to add the urls direct into the config file like this
```
Configuration: array(20) {
  ["CONFIG_FILE"] => string(28) "/etc/pihole-updatelists.conf"
  ["GRAVITY_DB"] => string(22) "/etc/pihole/gravity.db"
  ["LOCK_FILE"] => string(33) "/var/lock/pihole-updatelists.lock"
  ["LOG_FILE"] => string(0) ""
  ["ADLISTS_URL"] => string(74) "https://raw.githubusercontent.com/mhhakim/pihole-blocklist/master/porn.txt"
  ["WHITELIST_URL"] => string(0) ""
  ["REGEX_WHITELIST_URL"] => string(0) ""
  ["BLACKLIST_URL"] => string(0) ""
  ["REGEX_BLACKLIST_URL"] => string(0) ""
  ["COMMENT"] => string(29) "Managed by pihole-updatelists"
  ["GROUP_ID"] => int(0)
  ["PERSISTENT_GROUP"] => bool(false)
  ["REQUIRE_COMMENT"] => bool(true)
  ["UPDATE_GRAVITY"] => bool(true)
  ["VACUUM_DATABASE"] => bool(false)
  ["VERBOSE"] => bool(false)
  ["DEBUG"] => bool(true)
  ["DOWNLOAD_TIMEOUT"] => int(60)
  ["IGNORE_DOWNLOAD_FAILURE"] => bool(false)
  ["GIT_BRANCH"] => string(6) "master"
}
Options: array(2) {
  ["version"] => bool(false)
  ["debug"] => bool(false)
}
```
But then when i run piholeupdatelists the list is getting disabled again.
And how can i assure that the script will execute on saturday between 03:00 and 04:00 am?

`sudo systemctl edit pihole-updatelists.timer`

is tempty

**Comment by jacklul** [comment]
> Guess i understood. I have to add the urls direct into the config file like this
> 
> ```
> Configuration: array(20) {
>   ["CONFIG_FILE"] => string(28) "/etc/pihole-updatelists.conf"
>   ["GRAVITY_DB"] => string(22) "/etc/pihole/gravity.db"
>   ["LOCK_FILE"] => string(33) "/var/lock/pihole-updatelists.lock"
>   ["LOG_FILE"] => string(0) ""
>   ["ADLISTS_URL"] => string(74) "https://raw.githubusercontent.com/mhhakim/pihole-blocklist/master/porn.txt"
>   ["WHITELIST_URL"] => string(0) ""
>   ["REGEX_WHITELIST_URL"] => string(0) ""
>   ["BLACKLIST_URL"] => string(0) ""
>   ["REGEX_BLACKLIST_URL"] => string(0) ""
>   ["COMMENT"] => string(29) "Managed by pihole-updatelists"
>   ["GROUP_ID"] => int(0)
>   ["PERSISTENT_GROUP"] => bool(false)
>   ["REQUIRE_COMMENT"] => bool(true)
>   ["UPDATE_GRAVITY"] => bool(true)
>   ["VACUUM_DATABASE"] => bool(false)
>   ["VERBOSE"] => bool(false)
>   ["DEBUG"] => bool(true)
>   ["DOWNLOAD_TIMEOUT"] => int(60)
>   ["IGNORE_DOWNLOAD_FAILURE"] => bool(false)
>   ["GIT_BRANCH"] => string(6) "master"
> }
> Options: array(2) {
>   ["version"] => bool(false)
>   ["debug"] => bool(false)
> }
> ```
> 
> But then when i run piholeupdatelists the list is getting disabled again.
> And how can i assure that the script will execute on saturday between 03:00 and 04:00 am?
> 
> `sudo systemctl edit pihole-updatelists.timer`
> 
> is tempty

ADLIST_URL must point to <ins>list of adlists</ins>, not to adlist. [This is how](https://v.firebog.net/hosts/lists.php?type=tick) correct list should look like.

**Comment by StifflersMoM69** [comment]
Hi thanks a lot.
Finally i understood (hopefully) and its working.
May i ask 1 last question please?

Is it possible to add the Lists to more then one specific groups? For example every List should be added by default to groups with ID 0 and 2
`GROUP_ID=0;2`
seems not working

**Comment by jacklul** [comment]
`GROUP_ID=2` will do that - add to both group with ID and the default (ID=0) group
If you make the number negative (`GROUP_ID=-2`) it will add only to the specified group
(it's all in the readme)

**Comment by StifflersMoM69** [comment]
Thanks, i read the README but some parts where really hard for me to understand without some examples.
