### ISSUE TITLE
Docker endless reboot loop on startup

### ISSUE THREAD

**Issue by omares** [jacklul/pihole-updatelists#49]
Hey,

I ran into the issue that has put the docker container into an endless reboot loop. The `pihole-updatelists` script was unable to fetch any of the lists, as no DNS server was available, which caused the startup script to exit with an error, which further led to docker killing the container.

In my scenario, my network/DNS setup was "finished", meaning that all DNS requests are sent to the Pi-Hole. As soon as the Pi-Hole is down, obviously, requests to any domain will fail. The `jacklul/pihole` image runs the `pihole-updatelists` script on start, which tries to fetch entries from the provided lists. Given the setup from above the script is unable to fetch anything and the startup process goes 💥 

Here is the full log

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-pihole-updatelists.sh: executing... 
removed '/etc/pihole-updatelists.conf'
'/etc/pihole-updatelists.conf' -> '/etc/pihole-updatelists/pihole-updatelists.conf'
removed '/etc/cron.d/pihole-updatelists'
'/etc/cron.d/pihole-updatelists' -> '/etc/pihole-updatelists/crontab'

      Pi-hole's Lists Updater by Jack'lul     
 https://github.com/jacklul/pihole-updatelists

Opened gravity database: /etc/pihole/gravity.db (21.08 MB)

Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... Could not resolve host: v.firebog.net
 

Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'...[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

```

Is there an option to disable/prevent this behaviour? If not, would it make sense to add a `start/boot` option, that would stop the script from erroring out?

**Comment by jacklul** [comment]
Pushed testing fix on dev branch, docker hub is rebuilding the image, try pulling 'jacklul/pihole:dev' image after it's done and checking

**Comment by omares** [comment]
You are right, your fix resolves the issue with your changes but the docker container stills fails to start as now the pihole startup procedure exits with an error. The only idea I had to resolve this, was adding a public DNS server address to the machine running the pihole.

**Comment by jacklul** [comment]
> You are right, your fix resolves the issue with your changes but the docker container stills fails to start as now the pihole startup procedure exits with an error. The only idea I had to resolve this, was adding a public DNS server address to the machine running the pihole.

I believe this is what their installation procedure said? They even use cloudflare's DNS in their example configs

**Comment by omares** [comment]
Do you mean this? 
![image](https://user-images.githubusercontent.com/1375307/102926446-49913100-4495-11eb-82b0-48962ca89989.png)

**Comment by jacklul** [comment]
> Do you mean this?
> ![image](https://user-images.githubusercontent.com/1375307/102926446-49913100-4495-11eb-82b0-48962ca89989.png)

Yep, when I tested the script in VM it didn't start without this

**Comment by omares** [comment]
Ah I see my error, I mixed the `DNS1` environment variable and the `DNS` docker settings. It all works now, sorry for the confusion. Feel free to close the issue.
