### ISSUE TITLE
Comments in adlist are not being ignored

### ISSUE THREAD

**Issue by p1r473** [jacklul/pihole-updatelists#5]
Hello,
After adding comments to the adlist, I am seeing them in my Pihole.
I think you should parse out the comments.

![image](https://user-images.githubusercontent.com/9235633/79701744-81dcd180-826d-11ea-9253-ea58be4b8f61.png)

**Comment by jacklul** [comment]
This will be fixed

**Comment by p1r473** [comment]
I will test
thanks!

**Comment by p1r473** [comment]
Looks like this worked, thanks!
![image](https://user-images.githubusercontent.com/9235633/79763478-256fc580-82f2-11ea-9e0c-857089a4bcd0.png)

![image](https://user-images.githubusercontent.com/9235633/79763499-2bfe3d00-82f2-11ea-8353-65635d107472.png)
