### ISSUE TITLE
Different adlist per group

### ISSUE THREAD

**Issue by notDavid** [jacklul/pihole-updatelists#50]
Hi,

Is it currently possible to somehow assign different lists to different groups? For example to set https://v.firebog.net/hosts/lists.php?type=tick for group "Default" and "https://v.firebog.net/hosts/lists.php?type=nocross" for "Group2" ?

Thanks.

**Comment by jacklul** [comment]
You can use `pihole-updatelists --config=/home/pi/pihole-updatelists2.conf` to execute the script using different config, in this scenario the comment must be changed to something else for the second config.

**Comment by notDavid** [comment]
Great, I will try that. thank you! :)

**Comment by notDavid** [comment]
@jacklul One more question; If **new urls** are added to the adlist from "Group2", wouldn't those also be added to the "Default" group?

Because the comment in the config says:

_All inserted adlists and domains will have this additional group ID assigned
0 is the default group **to which all entries are added anyway**
GROUP_ID=2_

**Comment by jacklul** [comment]
Make the number negative to not add to the default group.
You might actually run into some issues with this setup as both lists share common entries, I suggest users/devices assigned to group 2 be also assigned to default group as entries already existing in the default group (from default config) will not have the secondary group assigned.

The alternative is setting `PERSISTENT_GROUP=true` but in this case you can't use negative `GROUP_ID` as this functionality will remove the entry from the default group on whichever config has the negative `GROUP_ID`.

What I would try:
Config2 must run before default config, both configs need ` PERSISTENT_GROUP=true`.
In this scenario config2 will remove some entries from the default group but the default config "should" re-add it.
