### ISSUE TITLE
Error while running sudo pihole-updatelists --update

### ISSUE THREAD

**Issue by dorminyk** [jacklul/pihole-updatelists#53]
Getting the following error while trying to run above command.

_sudo pihole-updatelists --update_
Git branch: master
Local checksum: 4a533ede9b614e4a6ccac600ddc3cf69
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /usr/local/sbin/pihole-updatelists on line 446
**PHP Warning:  file_get_contents(): Failed to enable crypto in /usr/local/sbin/pihole-updatelists on line 446
PHP Warning:  file_get_contents(https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/pihole-updatelists.php): failed to open stream: operation failed in /usr/local/sbin/pihole-updatelists on line 446**
Failed to check remote script: failed to open stream: operation failed

**Comment by jacklul** [comment]
Your machine might not have OpenSSL installed - `apt install openssl`

**Comment by jacklul** [comment]
Closed due to inactivity, feel free to reopen this if the issue is not fixed for you
