### ISSUE TITLE
Introduce docker version tags

### ISSUE THREAD

**Issue by omares** [jacklul/pihole-updatelists#55]
Hey,

right now you only provide [the `:latest` and `:dev` tags](https://hub.docker.com/r/jacklul/pihole/tags). Would it be possible to start introducing version tags? 

This would enable users of the image to pin the version in their setups, helping to prevent unintended upgrades, which are kind of no fun for critical network components.

Cheers

**Comment by jacklul** [comment]
Version tags of what? Script or Pi-hole's versions?

**Comment by omares** [comment]
For your customized docker releases that include your update list script

**Comment by jacklul** [comment]
If the user wants to stay on the specific script version they can always clone this repo and use provided dockerfile or create their own using local files for install.

I have no idea how to achieve this using current multiarch build technique on dockerhub, if you're up for the task then go for it.

**Comment by jacklul** [comment]
I can see already a problem with such building
The versioned build will contain old Pi-hole's version and dockerhub will not update it's image inside jacklul/pihole:(versionedtag)

Needs a solution

**Comment by jacklul** [comment]
Closed - use custom Dockerfile to achieve this.
