### ISSUE TITLE
Can't find systemd or crontab entry

### ISSUE THREAD

**Issue by rxng** [jacklul/pihole-updatelists#56]
Hi there, the service is not created, as in it is not in the list when typing systemctl --type=service

It also doesn't seem to be in crontab

How can we check that it is going to auto update?

**Comment by jacklul** [comment]
It's timer-only service - it won't be listed there. `systemctl list-timers`

**Comment by rxng** [comment]
it doesn't seem to be in the timer list either @jacklul 

maybe I am missing something?

NEXT                          LEFT       LAST                          PASSED       UNIT                         ACTIVATES
Thu 2021-01-14 16:39:00 AEDT  17min left Thu 2021-01-14 16:09:35 AEDT  11min ago    phpsessionclean.timer        phpsessionclean.service
Thu 2021-01-14 22:37:04 AEDT  6h left    Thu 2021-01-14 13:35:35 AEDT  2h 45min ago apt-daily.timer              apt-daily.service
Thu 2021-01-14 23:55:00 AEDT  7h left    Thu 2021-01-14 05:18:09 AEDT  11h ago      log2ram-daily.timer          log2ram-daily.service
Fri 2021-01-15 00:00:00 AEDT  7h left    Thu 2021-01-14 05:18:19 AEDT  11h ago      logrotate.timer              logrotate.service
Fri 2021-01-15 00:00:00 AEDT  7h left    Thu 2021-01-14 05:18:20 AEDT  11h ago      man-db.timer                 man-db.service
Fri 2021-01-15 06:56:31 AEDT  14h left   Thu 2021-01-14 08:17:23 AEDT  8h ago       apt-daily-upgrade.timer      apt-daily-upgrade.service
Fri 2021-01-15 09:08:37 AEDT  16h left   Thu 2021-01-14 09:08:37 AEDT  7h ago       systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service

**Comment by jacklul** [comment]
Does any of these turn out anything:
`ls /etc/systemd/system/pihole-updatelists.*`
`ls /etc/cron.d/pihole-updatelists`

**Comment by jacklul** [comment]
Closed due to inactivity, feel free to reopen this if the issue is not fixed for you
