### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by batZen23** [jacklul/pihole-updatelists#60]
when trying to update i get this new error in the last days, before it worked well.

pi@PiHole:~ $ sudo pihole-updatelists --update
Git branch: master
Local checksum: 4a533ede9b614e4a6ccac600ddc3cf69
Failed to check remote script: Unknown error

**Comment by jacklul** [comment]
Re-run install script
https://github.com/jacklul/pihole-updatelists/issues/57
