### ISSUE TITLE
Domains on blocklist: -2

### ISSUE THREAD

**Issue by dMopp** [jacklul/pihole-updatelists#62]
After running the Script, no domains are on blocklist anymore. After running pihole restartdns is it working again..

**Comment by dMopp** [comment]
More Informations:
Vacuum is active and i have ~1.3Million domains on blacklist.

**Comment by jacklul** [comment]
Need some more information.
`pihole-updatelists --debug --version`

**Comment by dMopp** [comment]
Checksum: 5eb574c0a2dca2c54d7232b02e84e505
Git branch: master
OS: Linux unifi 5.9.0-0.bpo.2-amd64 #1 SMP Debian 5.9.6-1~bpo10+1 (2020-11-19) x86_64
PHP: 7.3.19-1~deb10u1 NTS
SQLite: 3.27.2
cURL: 7.64.0
Pi-hole Core: v5.2.4-0-gcbfb58f (master)
Pi-hole Web: v5.3.1-0-g704e5d4 (master)
Pi-hole FTL: v5.5.1 (master)
Configuration: array(20) {
  ["CONFIG_FILE"] => string(28) "/etc/pihole-updatelists.conf"
  ["GRAVITY_DB"] => string(22) "/etc/pihole/gravity.db"
  ["LOCK_FILE"] => string(33) "/var/lock/pihole-updatelists.lock"
  ["LOG_FILE"] => string(22) "/var/log/update-pihole"
  ["ADLISTS_URL"] => string(50) "https://v.firebog.net/hosts/lists.php?type=nocross"
  ["WHITELIST_URL"] => string(82) "https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt"
  ["REGEX_WHITELIST_URL"] => string(0) ""
  ["BLACKLIST_URL"] => string(0) ""
  ["REGEX_BLACKLIST_URL"] => string(71) "https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list"
  ["COMMENT"] => string(29) "Managed by pihole-updatelists"
  ["GROUP_ID"] => int(0)
  ["PERSISTENT_GROUP"] => bool(false)
  ["REQUIRE_COMMENT"] => bool(true)
  ["UPDATE_GRAVITY"] => bool(true)
  ["VACUUM_DATABASE"] => bool(true)
  ["VERBOSE"] => bool(true)
  ["DEBUG"] => bool(true)
  ["DOWNLOAD_TIMEOUT"] => int(60)
  ["IGNORE_DOWNLOAD_FAILURE"] => bool(false)
  ["GIT_BRANCH"] => string(6) "master"
}
Options: array(2) {
  ["debug"] => bool(false)
  ["version"] => bool(false)
}

Git branch: master
Local checksum: 5eb574c0a2dca2c54d7232b02e84e505
Remote checksum: 5eb574c0a2dca2c54d7232b02e84e505
The script is up to date!

**Comment by jacklul** [comment]
Looks ok to me, have you tried without vacuuming option?
Maybe something changed in Pi-hole and that option is now unsafe

**Comment by dMopp** [comment]
Looks working fine without Vacuum. Maybe implement a restart if vacuum=true? (Tried with systemd but does not work)

**Comment by jacklul** [comment]
I rather not restart the service from within the script, I do send a signal to the pihole-FTL requesting reload though.

This should do:
```
[Service]
Type=oneshot
ExecStartPost=/usr/local/bin/pihole restartdns
```
https://github.com/jacklul/pihole-updatelists#running-custom-commands-beforeafter-scheduled-run

**Comment by dMopp** [comment]
Ah, oneshot only affects timed runs, good to know. Because i already adjusted the systemd file without success before i created the Ticket. 

Anyway, Maybe it is a good Idea to trigger a restart if vacuum=true as default behavior from now on. So far, i can live with the oneshot hotfix for scheduled runs, thx for helping out.

**Comment by jacklul** [comment]
Currently I'm considering removing vacuum option completely. (it can still be done with service override method)
