### ISSUE TITLE
Adding Discord/Webhook Notification

### ISSUE THREAD

**Issue by quorn23** [jacklul/pihole-updatelists#63]
Hi,

I have been using the piholeparser [https://github.com/deathbybandaid/piholeparser](https://github.com/deathbybandaid/piholeparser) in the past, but the project is sadly dead, so i disabled my local installation of it per today and switched to your script. 

I had a discord notification added to the script (simple curl post to a webhook), that notified me, when the script had ran.
(I also added a small script posting the diskspace and tags my user if a threshold is reached, but this is probably rather out of scope)

See an example here: [https://github.com/quorn23/piholeparser/blob/master/scripts/TopLevelScripts/90-Completing-End-Tasks/90-Discord-Message.sh](https://github.com/quorn23/piholeparser/blob/master/scripts/TopLevelScripts/90-Completing-End-Tasks/90-Discord-Message.sh)

So opening this issue here to either request if there would be the possibility to add it to the setup (as for example having the webhook url in the configuration file), or to point me to the right line in the what file to add it manually.

Thanks, Gabe

PS: I know there are "bigger, better" solutions for notifications like Apprise, but i rather keep the footprint and requirements small, webhooks are simple and understood by smart home solutions etc.

**Comment by jacklul** [comment]
https://github.com/jacklul/pihole-updatelists#running-custom-commands-beforeafter-scheduled-run
```
[Service]
Type=oneshot
ExecStartPost=curl asdf
```

Will affect only scheduled runs.
