### ISSUE TITLE
Fetching Remote List Problems

### ISSUE THREAD

**Issue by corasaniti** [jacklul/pihole-updatelists#65]
Hi,

Hi from today I have this problem when I start the Docker container.
All my configurations are correct

Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... HTTP request failed with status code 0

Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... HTTP request failed with status code 0

Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... HTTP request failed with status code 0

First everything worked correctly I didn't change any options.
Thank you

**Comment by jacklul** [comment]
Does the machine hosting the docker container have working DNS access and does your docker compose have fallback dns set?
```yaml
dns:
   - 127.0.0.1
   - 1.1.1.1
```

It seems like due mistake on my end the real error message isn't show, I'm pushing update that should fix this.
"HTTP request failed with status code 0" isn't telling a lot as it was meant to return real HTTP response code, if it is 0 then something else happened (probably dns resolution failure).

**Comment by corasaniti** [comment]
Hi thanks for your reply...
Thisi si my docker-compose.yml 
Version is "2" because Portainer doesn't not support version "3"

version: "2"

services:
  pihole:
    container_name: pihole.updatelist
    hostname: pihole.updatelist
    image: jacklul/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Rome'
    volumes:
      - '/home/pi/docker/pihole-updatelist/etc-pihole:/etc/pihole'
      - '/home/pi/docker/pihole-updatelist/etc-dnsmasq.d:/etc/dnsmasq.d'
      - '/home/pi/docker/pihole-updatelist/etc-pihole-updatelists:/etc/pihole-updatelists'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    
    
if I perform wget https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt from host I can download it correctly
Thanks again

**Comment by corasaniti** [comment]
Update ...
If I do get from inside the container I get this error ...

`root@pihole:~# wget https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
--2021-02-18 19:02:33--  https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 
failed: Temporary failure in name resolution.
wget: unable to resolve host address 'raw.githubusercontent.com'
root@pihole:~#`

Thanks

**Comment by corasaniti** [comment]
`
This is my log

 https://github.com/jacklul/pihole-updatelists
Opened gravity database: /etc/pihole/gravity.db (3.53 MB)
Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... Could not resolve host: v.firebog.net
Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... Could not resolve host: raw.githubusercontent.com
Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... Could not resolve host: raw.githubusercontent.com

Finished with 3 error(s) in 60.32 seconds.
[cont-init.d] 10-pihole-updatelists.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-pihole-updatelists.sh: executing... 
      Pi-hole's Lists Updater by Jack'lul     
 https://github.com/jacklul/pihole-updatelists


Opened gravity database: /etc/pihole/gravity.db (3.53 MB)
Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... Could not resolve host: v.firebog.net 
Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... Could not resolve host: raw.githubusercontent.com
Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... Could not resolve host: raw.githubusercontent.com

Finished with 3 error(s) in 60.33 seconds.
[cont-init.d] 10-pihole-updatelists.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-pihole-updatelists.sh: executing... 
      Pi-hole's Lists Updater by Jack'lul     
 https://github.com/jacklul/pihole-updatelists
Opened gravity database: /etc/pihole/gravity.db (3.53 MB)

Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... Could not resolve host: v.firebog.net
 
Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... Could not resolve host: raw.githubusercontent.com
Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... Could not resolve host: raw.githubusercontent.com
Finished with 3 error(s) in 60.32 seconds.
[cont-init.d] 10-pihole-updatelists.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-pihole-updatelists.sh: executing... 
      Pi-hole's Lists Updater by Jack'lul     
 https://github.com/jacklul/pihole-updatelist

Opened gravity database: /etc/pihole/gravity.db (3.53 MB)
Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... Could not resolve host: v.firebog.net
Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... Could not resolve host: raw.githubusercontent.com

`

**Comment by corasaniti** [comment]
Update  i replaced the dns of cloudfare with that of google in docker-compose

     dns:
       - 127.0.0.1
       - 1.1.1.1

with

     dns:
       - 127.0.0.1
       - 8.8.8.8

and everything seems to be going now If you have any news let me know
thank you
Piero

**Comment by jacklul** [comment]
So it's fixed ?

**Comment by corasaniti** [comment]
No!!  On another Raspberry I have installed the standard image of pihole:latest with Cloudfare DNS in docker compose and it works perfectly

     dns:
       - 127.0.0.1
       - 1.1.1.1

**Comment by jacklul** [comment]
Have you tried the latest image? I pushed small change and the error message should be different now

**Comment by corasaniti** [comment]
Of course but the errror is DNS 1.1.1.1 from my area....
ping 1.0.0.1 works
ping 1.1.1.1 I cant reach it

**Comment by jacklul** [comment]
Then use 1.0.0.1 if the script works with it

**Comment by jacklul** [comment]
Closed due to inactivity, feel free to reopen this if the issue is not fixed for you
