### ISSUE TITLE
Adlists disabled after every update

### ISSUE THREAD

**Issue by saschafiedler** [jacklul/pihole-updatelists#66]
I have noticed that every Saturday after updating the adlists, they are disabled, so that they always have to be manually re-enabled afterwards. Is this an intended behaviour or a configuration error?

**Comment by jacklul** [comment]
Sounds like configuration error.
Please show me the output of `pihole-updatelists --debug --version`.

**Comment by saschafiedler** [comment]
Thank you for your fast reply!

`Checksum: eded553d41d298676220a993b56d78c6
Git branch: master
OS: Linux Raspberry-Pi-Zero 4.19.118+ #1311 Mon Apr 27 14:16:15 BST 2020 armv6l
PHP: 7.3.19-1~deb10u1 NTS
SQLite: 3.27.2
Pi-hole Core: v5.2.4-0-gcbfb58f (master)
Pi-hole Web: v5.4-0-g989e1ba (master)
Pi-hole FTL: v5.7 (master)
Configuration: array(19) {
  ["CONFIG_FILE"] => string(28) "/etc/pihole-updatelists.conf"
  ["GRAVITY_DB"] => string(22) "/etc/pihole/gravity.db"
  ["LOCK_FILE"] => string(33) "/var/lock/pihole-updatelists.lock"
  ["LOG_FILE"] => string(0) ""
  ["ADLISTS_URL"] => string(47) "https://v.firebog.net/hosts/lists.php?type=tick"
  ["WHITELIST_URL"] => string(82) "https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt"
  ["REGEX_WHITELIST_URL"] => string(0) ""
  ["BLACKLIST_URL"] => string(0) ""
  ["REGEX_BLACKLIST_URL"] => string(71) "https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list"
  ["COMMENT"] => string(29) "Managed by pihole-updatelists"
  ["GROUP_ID"] => int(0)
  ["REQUIRE_COMMENT"] => bool(true)
  ["UPDATE_GRAVITY"] => bool(true)
  ["VACUUM_DATABASE"] => bool(false)
  ["VERBOSE"] => bool(false)
  ["DEBUG"] => bool(true)
  ["DOWNLOAD_TIMEOUT"] => int(60)
  ["IGNORE_DOWNLOAD_FAILURE"] => bool(false)
  ["GIT_BRANCH"] => string(6) "master"
}
Options: array(2) {
  ["debug"] => bool(false)
  ["version"] => bool(false)
}

Git branch: master
Local checksum: eded553d41d298676220a993b56d78c6
Remote checksum: c4b46c62ab7c0852d2e0a850bae82e5d
Update is available!`

**Comment by jacklul** [comment]
Configuration seems ok.
Can you update the script with `pihole-updatelists --update` and then run `pihole-updatelists --no-gravity` and check if the issue happens again?

**Comment by saschafiedler** [comment]
All adlists entries get disabled.
I just did the update when I saw the notice on the output. Thank you for your support. I'll get back to you next Saturday.

**Comment by jacklul** [comment]
Also I notice now there was `PERSISTENT_GROUP` missing from the debug output, are you running version from `develop` branch? (that option was removed there but the update is not yet pushed as stable as it isn't tested well)

You should definitely use only version from the `master` branch.

**Comment by saschafiedler** [comment]
As far as I know, I have only ever had the master branch in operation. After the update, ´PERSISTENT_GROUP´ now appears in the debug output.

´´´
Checksum: c4b46c62ab7c0852d2e0a850bae82e5d
Git branch: master
OS: Linux Raspberry-Pi-Zero 4.19.118+ #1311 Mon Apr 27 14:16:15 BST 2020 armv6l
PHP: 7.3.19-1~deb10u1 NTS
SQLite: 3.27.2
cURL: Unavailable
Pi-hole Core: v5.2.4-0-gcbfb58f (master)
Pi-hole Web: v5.4-0-g989e1ba (master)
Pi-hole FTL: v5.7 (master)
Configuration: array(20) {
  ["CONFIG_FILE"] => string(28) "/etc/pihole-updatelists.conf"
  ["GRAVITY_DB"] => string(22) "/etc/pihole/gravity.db"
  ["LOCK_FILE"] => string(33) "/var/lock/pihole-updatelists.lock"
  ["LOG_FILE"] => string(0) ""
  ["ADLISTS_URL"] => string(47) "https://v.firebog.net/hosts/lists.php?type=tick"
  ["WHITELIST_URL"] => string(82) "https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt"
  ["REGEX_WHITELIST_URL"] => string(0) ""
  ["BLACKLIST_URL"] => string(0) ""
  ["REGEX_BLACKLIST_URL"] => string(71) "https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list"
  ["COMMENT"] => string(29) "Managed by pihole-updatelists"
  ["GROUP_ID"] => int(0)
  ["PERSISTENT_GROUP"] => bool(false)
  ["REQUIRE_COMMENT"] => bool(true)
  ["UPDATE_GRAVITY"] => bool(true)
  ["VACUUM_DATABASE"] => bool(false)
  ["VERBOSE"] => bool(false)
  ["DEBUG"] => bool(true)
  ["DOWNLOAD_TIMEOUT"] => int(60)
  ["IGNORE_DOWNLOAD_FAILURE"] => bool(false)
  ["GIT_BRANCH"] => string(6) "master"
}
Options: array(2) {
  ["debug"] => bool(false)
  ["version"] => bool(false)
}

Git branch: master
Local checksum: c4b46c62ab7c0852d2e0a850bae82e5d
Remote checksum: c4b46c62ab7c0852d2e0a850bae82e5d
The script is up to date!
´´´

**Comment by jacklul** [comment]
If the issue still happens on this version output of `pihole-updatelists --debug --verbose --no-gravity` might help.
Make sure the adlists are enabled on the web UI before running this.

**Comment by saschafiedler** [comment]
Hi! I'm a bit late, but I took another look at the list and there is some progress! Some lists are still enabled - but unfortunately not all of them.
I did a rough scan of the lists to see if the disabled lists might be corrupt and therefore disabled, but that doesn't seem to be the case - at least not for all - or are you seeing an error?

Enabled: https://v.firebog.net/hosts/AdguardDNS.txt
Disabled: https://v.firebog.net/hosts/Kowabit.txt

I also wanted to send you the log, but I currently get the following error I will now look into:
```
user@host:~ $ pihole-updatelists --debug --verbose --no-gravity
Unknown option(s): --no-graity
```

**Comment by jacklul** [comment]
Kowabit list does not exist on https://v.firebog.net/hosts/lists.php?type=tick that's why it got disabled.



> I also wanted to send you the log, but I currently get the following error I will now look into:
> 
> ```
> user@host:~ $ pihole-updatelists --debug --verbose --no-gravity
> Unknown option(s): --no-graity
> ```

Oh, that's a bug! Will fix it. I believe you can use `-n` instead of `--no-gravity`

**Comment by saschafiedler** [comment]
Oh sorry, I forgot that I had been playing around with the comments.
Even though it was probably my mistake and this solved my problem, I have created the log file: https://pastebin.com/N5cg3CHw

I will check again next Saturday.

**Comment by jacklul** [comment]
The log seems fine

**Comment by saschafiedler** [comment]
The update and deletion of the comments seems to have solved the problem. Thank you for your support!
