### ISSUE TITLE
Document sed command to disable default gravity update schedule

### ISSUE THREAD

**Issue by dakotahawkins** [jacklul/pihole-updatelists#67]
`sed -Ei '/pihole[[:space:]]+updateGravity/I,${s/^#*/#/;b};$q1' /etc/cron.d/pihole`

- Adds a `#` to the beginning of the appropriate line in `/etc/cron.d/pihole`
- Fails (returns 1) if the line isn't found
- Nondestructive
  - Preserves line content
  - If one (or more) `#`s are already present, replaces them with a single `#`

Will submit a PR adding this to `README.md`, but it could also be added to `pihole-updatelists` _iff_ `UPDATE_GRAVITY=true`.

FWIW I'm adding this to my custom update script right after running `pihole -up`, based on the advice that it might be necessary.

**Comment by dakotahawkins** [comment]
If you think this could/should be automated, let me know and I can prepare a separate issue and PR.

**Comment by jacklul** [comment]
> If you think this could/should be automated, let me know and I can prepare a separate issue and PR.

Yeah, some time ago I wanted to add it into install script but I decided to not interfere with Pi-hole as much as possible to not create new issues.
