### ISSUE TITLE
Some basic questions on use

### ISSUE THREAD

**Issue by tinjaw** [jacklul/pihole-updatelists#69]
Pi-hole v5.2.4 Web Interface v5.4 FTL v5.7

Should I see entries on the 
http://pi-hole.lan/admin/groups-domains.php?type=white
http://pi-hole.lan/admin/groups-domains.php?type=black
pages after the script is run? Or are those pages for my custom additional entries only? I am assuming the later.

What should I see on
http://pi-hole.lan/admin/groups-adlists.php
Presently I only see one entry, and it is
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Is that the expected behavior?

Lastly, what is the best way to see the entries that have been added to the pi-hole database by running your script?

Thanks.

**Comment by jacklul** [comment]
Everything this script adds should be visible on those pages, with "Managed by pihole-updatelists comment".

The script itself (without any configuration set) does nothing after installing it.

**Comment by tinjaw** [comment]
Something ain't working.

![2021-03-17_12-25-26](https://user-images.githubusercontent.com/110943/111510802-1ff64780-871c-11eb-9e89-2decca6a9cbc.png)

**Comment by tinjaw** [comment]
Found out the Default group was disabled. Enabling it fixed it.

**Comment by fafo17** [comment]
<img width="1440" alt="Schermata 2021-06-09 alle 11 31 06" src="https://user-images.githubusercontent.com/63503523/121330409-47714080-c916-11eb-8bfd-89830501dc4f.png">

I'm having the same problem, on "group managment/group" the default group is enabled
