### ISSUE TITLE
Help with config

### ISSUE THREAD

**Issue by 9myzwb4eh** [jacklul/pihole-updatelists#70]
Hi,
I setup pi hole in docker with folder based config for volumes. 
The docer ran the first time i setup and then i stopped and tried restarting tnd it failes with below log. I have added envrinoment varaibles adlist, whitelist and blacklist. 

The guide i followed for docker setup is from (other than extra volume config for pihole-updatelists. The screenshot for volume is attached as well.
<img width="1440" alt="config" src="https://user-images.githubusercontent.com/60201382/112675502-247ad880-8e5f-11eb-9c7b-383303c47787.png">

https://mariushosting.com/how-to-install-pi-hole-on-your-synology-nas/

[pihole.log](https://github.com/jacklul/pihole-updatelists/files/6213581/pihole.log)

**Comment by jacklul** [comment]
It's not configured, I suggest you read the readme carefully.

**Comment by jacklul** [comment]
Closed due to inactivity, feel free to reopen this if the issue is not fixed for you
