### ISSUE TITLE
Running pihole-updateslists Disables Some AdLists

### ISSUE THREAD

**Issue by AndyMandy112** [jacklul/pihole-updatelists#71]
Hi there,

I've just recently setup the pihole5-list-tool and your tool to manage and update my lists, however after running "pihole-updateslists"
a whole bunch of my AdLists are getting disabled. I cannot seem to work out why, can I please have some assistance?

Please let me know if you require any additional info :)

**Comment by AndyMandy112** [comment]
ubuntu@ubuntu:/opt$ pihole-updatelists --debug --version
Checksum: 321272492211e2ad9b85609329dbced3
Git branch: master
OS: Linux ubuntu 5.4.0-1032-raspi #35-Ubuntu SMP PREEMPT Fri Mar 19 20:52:40 UTC 2021 aarch64
PHP: 7.4.3 NTS
SQLite: 3.31.1
cURL: 7.68.0
Pi-hole Core: v5.2.4-0-gcbfb58f (master)
Pi-hole Web: v5.4-0-g989e1ba (master)
Pi-hole FTL: v5.7 (master)
Configuration: array(20) {
  ["CONFIG_FILE"] => string(28) "/etc/pihole-updatelists.conf"
  ["GRAVITY_DB"] => string(22) "/etc/pihole/gravity.db"
  ["LOCK_FILE"] => string(33) "/var/lock/pihole-updatelists.lock"
  ["LOG_FILE"] => string(0) ""
  ["ADLISTS_URL"] => string(47) "https://v.firebog.net/hosts/lists.php?type=tick"
  ["WHITELIST_URL"] => string(82) "https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt"
  ["REGEX_WHITELIST_URL"] => string(0) ""
  ["BLACKLIST_URL"] => string(0) ""
  ["REGEX_BLACKLIST_URL"] => string(71) "https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list"
  ["COMMENT"] => string(29) "Managed by pihole-updatelists"
  ["GROUP_ID"] => int(0)
  ["PERSISTENT_GROUP"] => bool(false)
  ["REQUIRE_COMMENT"] => bool(true)
  ["UPDATE_GRAVITY"] => bool(true)
  ["VACUUM_DATABASE"] => bool(false)
  ["VERBOSE"] => bool(false)
  ["DEBUG"] => bool(true)
  ["DOWNLOAD_TIMEOUT"] => int(60)
  ["IGNORE_DOWNLOAD_FAILURE"] => bool(false)
  ["GIT_BRANCH"] => string(6) "master"
}
Options: array(2) {
  ["debug"] => bool(false)
  ["version"] => bool(false)
}

Git branch: master
Local checksum: 321272492211e2ad9b85609329dbced3
Remote checksum: 321272492211e2ad9b85609329dbced3
The script is up to date!

**Comment by jacklul** [comment]
I assume you set "Managed by pihole-updatelists" comment to all adlists/domains?
Your custom entries must not have this comment otherwise script compares them with the remote lists and assumes they were removed and disables them.

**Comment by AndyMandy112** [comment]
I cleared AdLists and set as default, but this is still happening. I'll run through my workflow, can you please let me know where I've gone wrong.
With only the default two AdLists I used the List Tool to add 'Non-Crossed' & 'Allow List Only' lists, then I added my two custom lists, then I ran the two migrating lists and domain commands as per the Readme, thennn it's when I run the updatelists command that 16 lists get disabled.
![Screenshot 2021-04-05 013230](https://user-images.githubusercontent.com/81918885/113516787-cfea0280-95ae-11eb-9567-15f0b852d696.png)

**Comment by AndyMandy112** [comment]
My manually added AdLists aren't the ones being disabled.

**Comment by jacklul** [comment]
All I'm seeing is correct behaviour, disabled lists from your screenshots does not exist on https://v.firebog.net/hosts/lists.php?type=tick.

**Comment by AndyMandy112** [comment]
That's correct, I do want the non-crossed lists (which are the ones installed).

**Comment by AndyMandy112** [comment]
Oh! I understand what you mean now, lemme check my config file to see which URL I've specified there!

**Comment by AndyMandy112** [comment]
Solved!! - I'm a goose lol...

Thank you very much for your time with this :)
