### ISSUE TITLE
Cron to execute pihole-updatelists doesn't work inside docker container

### ISSUE THREAD

**Issue by Waringham** [jacklul/pihole-updatelists#72]
I am using your docker image jacklul/pihole:latest to launch a pihole container. The Docker container runs without any problems. I have adjusted the configuration file /etc-pihole-updatelists/crontab of the volume with my time. However, the script under /usr/local/sbin/pihole-updatelists in the container is not executed at the set time by the cron service. Inside the running container have checked the following:

```
waringham@services:~/docker/pihole$ docker exec -ti pihole-docker bash
root@pihole-docker:/# cat /etc/cron.d/pihole-updatelists
# Pi-hole's Lists Updater by Jack'lul
# https://github.com/jacklul/pihole-updatelists

25 13 * * *   root   /usr/local/sbin/pihole-updatelists

root@pihole-docker:/# ps -aux | grep -i cron| grep -v grep
root 409 0.0 0.0 204 4 ?        S 13:20 0:00 s6-supervise cron
root 428 0.0 0.0 5312 2300 ?        S 13:20 0:00 /usr/sbin/cron -f
```
I have already enabled logging in the configuration file pihole-updatelists.conf as well:

`LOG_FILE="-/var/log/pihole-updatelists.log"`

However, even after the set time of the cron job, there is no execution of the script in the log file.

A manual execution of the script inside the running docker container is working as expected.

Do you have any other idea?

**Comment by jacklul** [comment]
Could you check if the default Pi-hole's cron runs within the container?
I believe it writes to `/var/log/pihole_updateGravity.log`.

This should narrow down the troubleshooting

**Comment by Waringham** [comment]
Good question. There is no `/var/log/pihole_updateGravity.log `inside the container:

```
waringham@pihole-docker:/# ls -ltr /var/log/
total 448
-rw-rw-r-- 1 root     utmp          0 Apr  8 02:00 wtmp
-rw-rw---- 1 root     utmp          0 Apr  8 02:00 btmp
-rw-rw-r-- 1 root     utmp     292000 Apr 21 21:20 lastlog
-rw-r--r-- 1 root     root      32000 Apr 21 21:20 faillog
-rw-r--r-- 1 root     root       2446 Apr 21 21:20 alternatives.log
drwxr-xr-x 1 root     root       4096 Apr 21 21:41 apt
-rw-r--r-- 1 root     root      55938 Apr 21 21:41 dpkg.log
-rw-r--r-- 1 root     root      10866 Apr 24 13:20 pihole-updatelists.log
drwxr-xr-x 2 pihole   pihole     4096 Apr 24 13:20 pihole
drwxr-x--- 1 www-data www-data   4096 Apr 24 13:20 lighttpd
-rw-r--r-- 1 pihole   pihole    10589 Apr 24 13:21 pihole-FTL.log
-rw-r--r-- 1 pihole   pihole    27392 Apr 24 14:27 pihole.log
```

**Comment by jacklul** [comment]
Well, from my point of view it looks like the cron isn't running the jobs at all
You might also go into Pi-hole dashboard and click icons on the left side of each entry to see when were they last updated to check if it was Sunday ~3am

**Comment by Waringham** [comment]
Unfortunately I can't see that anymore, because I had triggered the update of the lists manually this morning. My entry in the cron file of pihole should run every Sunday 4:15am. I could change this entry to see if the cron job runs.

**Comment by Waringham** [comment]
I changed the cron file for the adlist update through pihole and it ran correctly 2 minutes ago. Now I also found under `/var/log/pihole_updateGravity.log` the log file for this. So it seems it is an issue of cron job of pihole-updatelists.

**Comment by jacklul** [comment]
> I changed the cron file for the adlist update through pihole and it ran correctly 2 minutes ago. Now I also found under `/var/log/pihole_updateGravity.log` the log file for this. So it seems it is an issue of cron job of pihole-updatelists.

Could you also temporarily change the time for the job in `/etc/cron.d/pihole-updatelists` and see if it runs?

**Comment by Waringham** [comment]
First, I directly modified the cron job file in the Docker container:

```
root@pihole-docker:/etc/cron.d# nano pihole-updatelists
root@pihole-docker:/etc/cron.d# cat pihole-updatelists
# Pi-hole's Lists Updater by Jack'lul
# https://github.com/jacklul/pihole-updatelists

03 16 * * root /usr/local/sbin/pihole-updatelists
```

Unfortunately, this did not bring any success.

I then changed the owner and group to root directly in the container:

```
root@pihole-docker:/etc/cron.d# ls -la /etc/pihole-updatelists/crontab
-rw-r--r-- 1 1000 1000 144 Apr 24 16:03 /etc/pihole-updatelists/crontab
root@pihole-docker:/etc/cron.d# chown root:root /etc/pihole-updatelists/crontab
root@pihole-docker:/etc/cron.d# ls -la /etc/pihole-updatelists/crontab
-rw-r--r-- 1 root root 144 Apr 24 16:03 /etc/pihole-updatelists/crontab
```

I checked the log file under `/var/log/pihole-updatelists.log` and had success!
Now the con job is executed correctly.

But how can we solve this problem now? Can you adjust the ownership directly in the build job?

**Comment by jacklul** [comment]
I'll just add `chmod` and `chown` commands to the startup script so they are corrected on every container start
This should do the trick, currently pushed to the dev branch and docker image

**Comment by Waringham** [comment]
Thank you for the quick support! It was a pleasure to solve this problem with you.
