### ISSUE TITLE
Option required that adlists are not updated by script when Docker container is started

### ISSUE THREAD

**Issue by Waringham** [jacklul/pihole-updatelists#73]
I need an option in the configuration file pihole-updatelists.conf that allows to turn on/off an update of the adlists on startup or restart of the Docker Container.

For Pi-Hole there is already an option **SKIPGRAVITYONBOOT** that allows to turn on/off an update of the Gravity database on startup or restart of the Docker container (see Environment Variables on https://hub.docker.com/r/pihole/pihole).

Would it be possible to provide a similar option for your script?

**Comment by jacklul** [comment]
Try pulling the "dev" image and verify that it is now respecting that variable, once you come back to me and say it's working I'm gonna push it to the master.

**Comment by Waringham** [comment]
It work's like a charm! Once again thank you for this super ultra fast response and solution.

**Comment by jacklul** [comment]
> It work's like a charm! Once again thank you for this super ultra fast response and solution.

Alright, I will be merging it into main image momentarily. :thumbsup:
