### ISSUE TITLE
Container init part of install.sh is not executed

### ISSUE THREAD

**Issue by vertrou** [jacklul/pihole-updatelists#74]
Hey I need to build my own docker image as I want to run pihole with unbound in a container. But since I don't want to do without the automatic update of the blocklists, I want to include your update script. As described in your readme, I have included these lines in the image. 
`RUN apt-get update && apt-get install -Vy php-cli php-sqlite3 php-intl php-curl`
`RUN wget -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/install.sh | bash`

This works well, the cron job and everything else is created. The problem is currently that when I build the image locally the value for the DOCKER parameter is zero.
`DOCKER=[ "$(awk -F/ '$2 == "docker"' /proc/self/cgroup)" == "" ] && echo "0" || echo "1" # Is this a Docker installation?`
Therefore the part in the script is not executed. Is there a way around this? I am currently building the image as follows:
`docker build . -t <TAG>`

**Comment by jacklul** [comment]
I'm not a docker expert, people were pretty positive that `[ "$(awk -F/ '$2 == "docker"' /proc/self/cgroup)" == "" ]` works for detecting if it is inside a docker, do you know of any other way of detecting it?

**Comment by vertrou** [comment]
Hey, thanks for the quick reply. Yes, you are right, if I build it inside a docker container with for example buildx then everything is detected correctly. So this part doesn't work with the normal docker build command. The only solution I can think of is to implement the possibility to give the script a parameter like `--is-docker`. However, I would also say that you don't really need this because you can simply build the image with buildx or other tools in a docker container.

**Comment by jacklul** [comment]
Can you check if `wget -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/install.sh | sudo bash /dev/stdin docker` works for you?

**Comment by vertrou** [comment]
Yes, that works too. Thank you.
