### ISSUE TITLE
Crash when restarting container

### ISSUE THREAD

**Issue by Alaksin** [jacklul/pihole-updatelists#75]
I just started using this but I've had a lot of struggles with it. Every time I restart the container it crashes. It works fine when I run it the first time with empty volumes, but if I restart it afterwards it just crashes. If I don't have ADLISTS_URL set in the .conf then it crashes because of that. If I set ADLISTS_URL it crashes because it can't resolve the host. I'm using my own unbound server on localhost, but it makes no difference if I use Google DNS or anything else. The script works fine if I run a clean container, and then run the script inside the container. BTW it took me a long time to figure out I actually have to run the script myself first. It doesnt say anything about it in the documentation so I assumed it would be handled by the container on startup. 

Anyway, this is the log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-pihole-updatelists.sh: executing... 
ownership of '/etc/pihole-updatelists/crontab' retained as root:root
ownership of '/etc/pihole-updatelists/pihole-updatelists.conf' retained as root:root
mode of '/etc/pihole-updatelists/crontab' retained as 0644 (rw-r--r--)
mode of '/etc/pihole-updatelists/pihole-updatelists.conf' retained as 0644 (rw-r--r--)

      Pi-hole's Lists Updater by Jack'lul     
 https://github.com/jacklul/pihole-updatelists

Opened gravity database: /etc/pihole/gravity.db (22.18 MB)

Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... Could not resolve host: v.firebog.net
 
Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... Could not resolve host: raw.githubusercontent.com
 
Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... Could not resolve host: raw.githubusercontent.com
 
Finished with 3 error(s) in 0.01 seconds.
[cont-init.d] 10-pihole-updatelists.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by jacklul** [comment]
Take a look at https://github.com/jacklul/pihole-updatelists/issues/49, I believe your container has no DNS access on startup

**Comment by Alaksin** [comment]
I did exactly the same as the other guy, confused the `dns` docker setting with the `DNS1` inv variable. Works like a charm now, thanks
