### ISSUE TITLE
Update entries

### ISSUE THREAD

**Issue by fafo17** [jacklul/pihole-updatelists#76]
NOOB here, followed the wiki with no problem but something is not working. I have no entries, and this make me ask some question.
Does the command -sudo pihole-updatelists --update, update only the scrip itself or it should work also to force the entries update?
Reading the past issues i've seen a problem like mine but i have already the default group enabled on the pihole.

<img width="1440" alt="Schermata 2021-06-09 alle 11 31 06" src="https://user-images.githubusercontent.com/63503523/121331842-8c49a700-c917-11eb-943c-31aad2da67cd.png">

**Comment by fafo17** [comment]
Answered myself, have to run sudo pihole-updatelists --force

**Comment by jacklul** [comment]
`sudo pihole-updatelists --update` - updates the script only, `--force` is optional switch to skip the confirmation prompt
`sudo pihole-updatelists` - runs the lists update, the command above does not run this

**Comment by fafo17** [comment]
Clear, and by default it runs a weekly update, right?

**Comment by jacklul** [comment]
> Clear, and by default it runs a weekly update, right?

Yes.

you can verify that the weekly schedule is set by running `systemctl list-timers pihole-updatelists` or `cat /etc/cron.d/pihole-updatelists` if your system is not using systemd. (only one of these will show output)
