### ISSUE TITLE
no service

### ISSUE THREAD

**Issue by alexdelli** [jacklul/pihole-updatelists#77]
Hi, if I run pihole-updatelists -v the output is Unknow option: 

if I run Systemctl status pihole-updatelists.service is Active: inactive 

the service is installed on a raspberry, not in a docker, a normal intall.

thank you

**Comment by jacklul** [comment]
> if I run Systemctl status pihole-updatelists.service is Active: inactive

Run `systemctl status pihole-updatelists.timer` instead, timer executes the service and it's inactive state is correct behaviour

> Hi, if I run pihole-updatelists -v the output is Unknow option:

Some more details on this?
