### ISSUE TITLE
Problem with installing on Debian

### ISSUE THREAD

**Issue by ahbanavi** [jacklul/pihole-updatelists#81]
Hey, I'm running pi-hole on Debian and while installing your package with install.sh script i find out that the script thinks I'm inside a docker but I'm not.  
I was mange to solve this by manually set DOCKER to 0.  

for more details (output of your docker check is 1):
![image](https://user-images.githubusercontent.com/39927312/129244025-34ea9fd2-d16d-4705-8526-48e4f4dc9526.png)

**Comment by jacklul** [comment]
Deployed test fix to dev branch, please try installing from it directly, I'm currently unable to test the fix myself.

**Comment by ahbanavi** [comment]
![image](https://user-images.githubusercontent.com/39927312/129266565-91312fcf-2b59-4acb-9b6d-b9c920b1f1ef.png)
yes that fix this issue, Thx.

**Comment by jacklul** [comment]
The fix is now in master branch.
