### ISSUE TITLE
Disable gravity update

### ISSUE THREAD

**Issue by Kopernikus1979** [jacklul/pihole-updatelists#85]
Hi,

I run 2 Pihole's on a HA setup and on the master Pi-Hole the updatelists script is running.
My Pihole's are set to auto update firmware & patches etc.
As a result I should disable the default gravity update each time there's an update.

However if let the default graivity update run and set gravity update in the config file to false, will I have the same result?
Or what would be different if I left the default gravity update and let the config to true?

**Comment by jacklul** [comment]
Just make sure the Pi-hole's schedule runs after script one and it will be ok.

I believe by default it's the other way around so you will have to re-adjust it.

**Comment by jacklul** [comment]
Closed due to inactivity, feel free to reopen if you still have any questions.
