### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by stevefxp1** [jacklul/pihole-updatelists#86]
Hello,

I noticed that three lists were not updated this past weekend:

https://phishing.army/download/phishing_army_blocklist_extended.txt
https://urlhaus.abuse.ch/downloads/hostfile/
https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt

I clicked on each, to check their date of creation and noticed it was today. I decided to run a simple update myself. What I found was that each got a connection refused in the log. Why would this be if I can just click on them in Pi-Hole and I am able to see the lists?

Thanks,
Steve

![Screenshot 2021-08-15 212013](https://user-images.githubusercontent.com/70986226/129499495-9557e249-c450-4cc7-aa75-d9b016a51075.png)

**Comment by jacklul** [comment]
You should ask about this on Pi-hole's repository as what you posted on the screenshot is their list update procedure.
What probably happens is that servers hosting those lists are refusing connection because user-agent string was banned to stop bots.

**Comment by stevefxp1** [comment]
I hear what you are saying but this is the output from your utility, so anyone who uses your utility will get the same result.

**Comment by jacklul** [comment]
> I hear what you are saying but this is the output from your utility, so anyone who uses your utility will get the same result.

That's why in the readme it's stated that `UPDATE_GRAVITY=true` simply runs `pihole updateGravity` command and shows the output
