### ISSUE TITLE
Move location of pihole-updatelists.conf

### ISSUE THREAD

**Issue by quielb** [jacklul/pihole-updatelists#88]
It would be nice of the location of pihole-updatelists.conf didn't live in /etc for container deployments. It's hard to bind mount over the top of /etc so that the config file lives and is managed outside of the lifecycle of the container.

Putting all the config in some like /config or /updatelists would make it easier to bind-mount a volume or use mounted config maps to manage the config outside of and not tied to the persistence of the container.

**Comment by jacklul** [comment]
Inside docker container it's symlinked to /etc/pihole-updatelists/pihole-updatelists.conf, the same folder also has also a symlink to crontab.
