### ISSUE TITLE
Changed behavior of group assignment?

### ISSUE THREAD

**Issue by count0x30** [jacklul/pihole-updatelists#93]
In my pihole-updatelists.conf, I use GROUP_ID to add one group to all my lists.  Then, for a just couple lists, I use the web interface to remove that group.  I used to do this just once per list, and my change would remain after an update.

Now, every time pihole-updatelists runs, it re-assigns that additional group, and I have to go in and make changes again.  It's as if PERSISTENT_GROUP is set to true, but I don't have it in my config file at all.

Is there any way for me edit my config to get the old behavior back?

**Comment by jacklul** [comment]
Does setting `PERSISTENT_GROUP=false` fixes the issue?

**Comment by count0x30** [comment]
Since the update only occurs once a week, and I don't regularly use all the devices on the network, I guess it took me a while to even realize there's a problem!

Setting `PERSISTENT_GROUP=false` doesn't fix the issue, and I get the message 
`Configuration option PERSISTENT_GROUP has been removed.`

No other errors or warnings appear in the log with `VERBOSE` and `DEBUG=true`.

As a specific example, I use pihole-updatelists to add group_id 1 to any new list that shows up in the non-crossed Firebog Big Blocklist Collection.  Then, I had removed that group_id off a select few lists.  This is what the log shows for such a list:
```
[INFO]   Exists: example.list
[DEBUG]  SQL Query: INSERT OR IGNORE INTO `adlist_by_group` (adlist_id, group_id) VALUES (62, 1)
[INFO]   Added 'example.list' to the group with ID = 1
```

Maybe this is the intended behavior for the script, and I just got used to the way things were?  Thank you for looking into this.

**Comment by jacklul** [comment]
Looks like some accidental merge with https://github.com/jacklul/pihole-updatelists/tree/config_sections branch happened and now it's merged. 
That branch had that option removed completely as it caused confusion.

**Comment by jacklul** [comment]
`PERSISTENT_GROUP` has been restored, it should now work.

**Comment by count0x30** [comment]
Yes, it works, brilliant!  

Also, thanks for pointing me at the config sections.  That's an incredibly useful feature.
