### ISSUE TITLE
Unable to setup cron after fresh install

### ISSUE THREAD

**Issue by tomini** [jacklul/pihole-updatelists#96]
Hi,
I redeployed Pi-hole and installed your script. Things changed and I am unable to get automated updating to work...
There were a lot of errors. Like I had to run  `sudo systemctl edit --force --full pihole-updatelists.timer`, but nothing happened...idk how I managed to make it. But even now I tried to change the timer to 60s after boot and it didn't add lists into Pi-hole AND `systemctl list-timers` doesn't mention your script.
Please help me :-(

Thanks a lot.

### sudo nano /etc/systemd/system/pihole-updatelists.timer
```
[Timer]
RandomizedDelaySec=60m
OnCalendar=Sat *-*-* 03:00:00
Persistent=true
```
### sudo systemctl edit pihole-updatelists.timer
```
### Editing /etc/systemd/system/pihole-updatelists.timer.d/override.conf
### Anything between here and the comment below will become the new contents of the file

[Timer]
RandomizedDelaySec=60m
OnCalendar=Sat *-*-* 04:00:00
Persistent=true

### Lines below this comment will be discarded

### /etc/systemd/system/pihole-updatelists.timer
# [Timer]
# RandomizedDelaySec=60m
# OnCalendar=Sat *-*-* 03:00:00
# Persistent=true
```
### sudo nano /etc/systemd/system/pihole-updatelists.service
```
[Service]
Type=oneshot
ExecStartPre=echo "before"
ExecStartPost=echo "after"
```
### sudo systemctl list-timers -all
```
NEXT                        LEFT          LAST                        PASSED       UNIT                         ACTIVATES
Sun 2022-01-09 20:06:04 CET 13min left    n/a                         n/a          systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Sun 2022-01-09 20:09:00 CET 16min left    Sun 2022-01-09 19:39:01 CET 13min ago    phpsessionclean.timer        phpsessionclean.service
Mon 2022-01-10 00:16:36 CET 4h 23min left Sun 2022-01-09 14:24:10 CET 5h 28min ago fstrim.timer                 fstrim.service

3 timers listed.
```

**Comment by jacklul** [comment]
> ### sudo nano /etc/systemd/system/pihole-updatelists.timer
> ```
> [Timer]
> RandomizedDelaySec=60m
> OnCalendar=Sat *-*-* 03:00:00
> Persistent=true
> ```

> ### sudo nano /etc/systemd/system/pihole-updatelists.service
> ```
> [Service]
> Type=oneshot
> ExecStartPre=echo "before"
> ExecStartPost=echo "after"
> ```

Are those full contents of those files? If yes then you edited wrong files while making the edits.
Please re-run the install script and edit them using only these commands:
`sudo systemctl edit pihole-updatelists.service`
`sudo systemctl edit pihole-updatelists.timer`

Do not use `--full` switch.

**Comment by tomini** [comment]
> Please re-run the install script

Just `wget -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/install.sh | sudo bash` or uninstall first?

**Comment by tomini** [comment]
> Please re-run the install script and edit them using only these commands: `sudo systemctl edit pihole-updatelists.service` `sudo systemctl edit pihole-updatelists.timer`
> 
> Never use `--full` switch unless you want to edit the main file (in 99% cases you don't).

This is what I get after uninstall and install:
```
sudo systemctl edit pihole-updatelists.timer
No files found for pihole-updatelists.timer.
Run 'systemctl edit --force --full pihole-updatelists.timer' to create a new unit.
```

**Comment by jacklul** [comment]
Have you checked that `/etc/cron.d/pihole-updatelists` exists?
Are you running full systemd distro?

**Comment by tomini** [comment]
> Are you running full systemd distro?

I am running DietPi 8.0.2

> Have you checked that `/etc/cron.d/pihole-updatelists` exists?

`sudo nano /etc/cron.d/pihole-updatelists` brings up this:
```
# Pi-hole's Lists Updater by Jack'lul
# https://github.com/jacklul/pihole-updatelists

24 3 * * 6   root   /usr/local/sbin/pihole-updatelists
```
> you could import .service and .timer files from the repository

I know how to download/clone, but I don't know how to do it with just one file... Otherwise after that I will just put `#` on the start of the line with `/usr/local/sbin/pihole-updatelists`.

Did I do something wrong? Or is it a bug?
The `.service` is for running command after `.timer` ran your script to update selected lists, right? I don't need anymore commands after that, but I will do it...just making sure I know what it does as it is a new thing for me. I was running version before all of this.

**Comment by tomini** [comment]
> > Are you running full systemd distro?
> 
> I am running DietPi 8.0.2
> 
> > Have you checked that `/etc/cron.d/pihole-updatelists` exists?
> 
> `sudo nano /etc/cron.d/pihole-updatelists` brings up this:
> 
> ```
> # Pi-hole's Lists Updater by Jack'lul
> # https://github.com/jacklul/pihole-updatelists
> 
> 24 3 * * 6   root   /usr/local/sbin/pihole-updatelists
> ```
> 
> > you could import .service and .timer files from the repository
> 
> I know how to download/clone, but I don't know how to do it with just one file... Otherwise after that I will just put `#` on the start of the line with `/usr/local/sbin/pihole-updatelists`.
> 
> Did I do something wrong? Or is it a bug? The `.service` is for running command after `.timer` ran your script to update selected lists, right? I don't need anymore commands after that, but I will do it...just making sure I know what it does as it is a new thing for me. I was running version before all of this.

PS: I installed and did everything NOT on `root` user, I used `dietpi` user. Is that a mistake?

**Comment by jacklul** [comment]
For clarification - if the linux distro is running with systemd then the install script will install .service and .timer files instead of crontab.

Dietpi seems to fail this check: https://github.com/jacklul/pihole-updatelists/blob/c2915b6f4708389e5e61f3a31f7231fa045ed762/install.sh#L16

**Comment by tomini** [comment]
> For clarification - if the linux distro is running with systemd then the install script will install .service and .timer files instead of crontab.
> 
> Dietpi seems to fail this check: https://github.com/jacklul/pihole-updatelists/blob/c2915b6f4708389e5e61f3a31f7231fa045ed762/install.sh#L16

So I have to do this then:
`If systemd is not available you just modify the crontab entry in /etc/cron.d/pihole-updatelists:

30 3 * * 6 root /home/pi/before.sh && /usr/local/sbin/pihole-updatelists && /home/pi/after.sh`

**Comment by jacklul** [comment]
No, if the systemd scheduler is available just copy .service and .timer files from the repository to `/etc/systemd/system` and comment the cron entry in `/etc/cron.d/pihole-updatelists`. 

Then you just follow the override instructions.

**Comment by jacklul** [comment]
I've updated the install script, you should be now able to do:
```bash
wget -O - https://raw.githubusercontent.com/jacklul/pihole-updatelists/master/install.sh | sudo bash /dev/stdin systemd
```

**Comment by tomini** [comment]
> I've updated the install script, you should be now able to do:

I used this modified install command (didn't uninstall), rebooted and timer is `n/a` in `-all` but at least it is there:
```
sudo systemctl list-timers -all
NEXT                        LEFT          LAST                        PASSED    UNIT                         ACTIVATES
Mon 2022-01-10 23:39:00 CET 1min 56s left Mon 2022-01-10 23:09:31 CET 27min ago phpsessionclean.timer        phpsessionclean.service
Mon 2022-01-10 23:51:13 CET 14min left    n/a                         n/a       systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Mon 2022-01-17 00:10:00 CET 6 days left   Mon 2022-01-10 01:30:22 CET 22h ago   fstrim.timer                 fstrim.service
n/a                         n/a           n/a                         n/a       pihole-updatelists.timer     pihole-updatelists.service
```

**Comment by jacklul** [comment]
I suspect because of your previous mistakes with the pihole-updatelists.timer it didn't start.
Try `sudo systemctl start pihole-updatelists.timer`.

**Comment by tomini** [comment]
> I suspect because of your previous mistakes with the pihole-updatelists.timer it didn't start. Try `sudo systemctl start pihole-updatelists.timer`.

sudo systemctl start pihole-updatelists.timer
`Job failed. See "journalctl -xe" for details.`
...
```
pihole-updatelists.timer: Refusing to start, unit pihole-updatelists.service to trigger not loaded.
Failed to start Weekly update of Pi-hole's lists.
```
...and then again this `Refusing to start...`

**Comment by jacklul** [comment]
Have you tried running `sudo systemctl daemon-reload` before mentioned command?
Can you show me the output of these:
```bash
cat /etc/systemd/system/pihole-updatelists.service
cat /etc/systemd/system/pihole-updatelists.service.d/override.conf
cat /etc/systemd/system/pihole-updatelists.timer
cat /etc/systemd/system/pihole-updatelists.timer.d/override.conf
```

**Comment by tomini** [comment]
> Can you show me the output of these:

```
dietpi@DietPi:~$ sudo systemctl daemon-reload
dietpi@DietPi:~$ sudo systemctl start pihole-updatelists.timer
Job failed. See "journalctl -xe" for details.
```
```
dietpi@DietPi:~$ cat /etc/systemd/system/pihole-updatelists.service
[Unit]
Description=Update Pi-hole's lists from remote sources
After=network-online.target multi-user.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/sbin/pihole-updatelists
TimeoutStartSec=infinity
```
```
dietpi@DietPi:~$ cat /etc/systemd/system/pihole-updatelists.service.d/override.conf
[Unit]
Description=Update Pi-hole's lists from remote sources
After=network-online.target multi-user.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/sbin/pihole-updatelists
TimeoutStartSec=infinitydietpi@DietPi:~$ cat /etc/systemd/system/pihole-updatelists.timer
[Unit]
Description=Weekly update of Pi-hole's lists

[Timer]
RandomizedDelaySec=60m
OnCalendar=Sat *-*-* 03:00:00
Persistent=true

[Install]
WantedBy=timers.target
```
```
dietpi@DietPi:~$ cat /etc/systemd/system/pihole-updatelists.timer.d/override.conf
[Unit]
Description=Weekly update of Pi-hole's lists

[Timer]
RandomizedDelaySec=60m
OnCalendar=Sat *-*-* 03:00:00
Persistent=true

[Install]
```

**Comment by jacklul** [comment]
It seems like you pasted whole service/timer file contents into override files, that's wrong.
Please remove the override files, execute `sudo systemctl daemon-reload` then re-do the overrides following the guide in the readme.

If you do not need to change the schedule do not make this step:
```bash
sudo systemctl edit pihole-updatelists.timer
```
```
[Timer]
RandomizedDelaySec=60m
OnCalendar=
OnCalendar=Sat *-*-* 03:00:00
```
Having `OnCalendar=` is essential as it resets the schedule from the parent file, without it you will run multiple schedules.
Obviously you replace the second with your schedule of choice (the one from the code is the default).

If you do not need to run commands before/after the script do not make this step:
```bash
sudo systemctl edit pihole-updatelists.service
```
```
[Service]
Type=oneshot
ExecStartPre=echo "before"
ExecStartPost=echo "after"
```

**Comment by tomini** [comment]
So I ran uninstall command and removed the /etc/systemd/system/pihole-updatelists.timer and .service folders with override files.
Why aren't they removed with uninstall command? And .conf wile as well. Just asking...
It works perfectly now with the `sudo bash /dev/stdin systemd` modification.

And about that:
> Make sure pihole-updatelists.service is not set to start on boot, to disable sudo systemctl disable `pihole-updatelists.service`.

Well `journalctl -xe -u pihole-updatelists.service` says:
```
-- Journal begins at Tue 2022-01-11 16:07:45 CET, ends at Tue 2022-01-11 16:15:50 CET. --
-- No entries --
```
So I guess it's all good as `sudo systemctl list-timers` gives me:
`Mon 2022-01-17 03:46:01 CET 5 days left   Tue 2022-01-11 15:41:58 CET 37min ago     pihole-updatelists.timer     pihole-updatelists.service`

**Comment by tomini** [comment]
Thank you so much <3
