### ISSUE TITLE
Container start not possible without changing the DNS servers temporarily

### ISSUE THREAD

**Issue by D3rSchurk3** [jacklul/pihole-updatelists#98]
The container needs a working dns server to start. If you use just one pihole and set it up as your dns server in router config it isn't reachable when the container is stopped. Therefore you need to change your router config temporarily every time you need to restart the container.

It's not such a big deal if you use two piholes, because one pihole is still reachable when you need to restart the other. But after a blackout or when you have to cut off the current, you would have to change the settings again.

Is there any way to avoid this?

**Comment by jacklul** [comment]
But isn't it also the case for the base pi-hole image? I specifically remember that the containers from Pi-hole team refused to start without working DNS.

**Comment by D3rSchurk3** [comment]
No, using the  base pi-hole image it works without a reachable dns server.

**Comment by D3rSchurk3** [comment]
Wouldn't it possible to skip the update process after like 5-10 minutes or so when no dns server is reachable? Would be cool if there were a variable for that.

**Comment by jacklul** [comment]
Well then, back when I was doing the docker implementation that was how their container worked.
I'll look into it when I have the time

**Comment by D3rSchurk3** [comment]
That's cool, thank you very much! ;)

**Comment by jacklul** [comment]
Could you change your image to :dev and tell me if it works for you and the script and gravity update is executed on boot?

**Comment by jacklul** [comment]
`docker exec -it pihole bash` will get you into container command line, then just check the log files.
_Replace `pihole` with container ID._

**Comment by D3rSchurk3** [comment]
pihole-updatelists.log:

Pi-hole's Lists Updater by Jack'lul
 https://github.com/jacklul/pihole-updatelists

Opened gravity database: /etc/pihole/gravity.db (23.04 MB)

Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... done (29 entries)
Processing... 29 exists

Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... done
Fetching WHITELIST from 'https://github.com/mmotti/pihole-regex/blob/master/whitelist.list'... done
Merging multiple lists... done (1469 entries)
Processing... 219 exists, 1247 invalid
List of invalid entries:
...

Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... done (14 entries)
Processing... 14 exists

Ignored 1247 invalid entries.
Finished successfully in 16.02 seconds.

======================================

pihole_updateGravity.log is empty

**Comment by jacklul** [comment]
Could you also check contents of the `/etc/cron.d/gravity-on-boot` file?
Could you check in the webinterface did the gravity update actually happenend? (Adlists page, look around adlists last update time if it's around minute late than of `pihole-updatelists.log`)

`https://github.com/mmotti/pihole-regex/blob/master/whitelist.list` is invalid, `https://raw.githubusercontent.com/mmotti/pihole-regex/master/whitelist.list` is the correct URL.

**Comment by D3rSchurk3** [comment]
gravity-on-boot: 

@reboot root PATH="$PATH:/usr/sbin:/usr/local/bin/" sleep 60 ; pihole updateGravity >/var/log/pihole_updateGravity.log || cat /var/log/pihole_updateGravity.log

No, the update did not happen. I've just rebuild the container using the dev image. Last update according to adlist page took place at about 5 hours ago whereas pihole-updateslists.log has just been updated when I've rebuild the container.

Thanks, just fixed the url ;)

**Comment by D3rSchurk3** [comment]
For example for "https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt"

dev image:
Health status of this list:	List unchanged upstream, Pi-hole used a local copy (OK)
This list was added to Pi-hole  	5 days ago (2022-01-08 14:44:13)
Database entry was last modified  	5 days ago (2022-01-08 14:44:13)
The list contents were last updated  	4 hours ago (2022-01-13 13:41:40)
Number of domains on this list:  	41792
Number of invalid domains on this list:  	0
Database ID of this list:	34

latest image on another pi:
Health status of this list:	List unchanged upstream, Pi-hole used a local copy (OK)
This list was added to Pi-hole  	a day ago (2022-01-12 18:35:46)
Database entry was last modified  	a day ago (2022-01-12 18:35:46)
The list contents were last updated  	an hour ago (2022-01-13 16:37:27)
Number of domains on this list:  	41846
Number of invalid domains on this list:  	0
Database ID of this list:	2

**Comment by jacklul** [comment]
I messed up the placement of that `sleep 60`.
Pushing update to dev image, could you update it, restart the container and verify the logs again?

**Comment by D3rSchurk3** [comment]
Now it seems to be working:

gravity-on-boot:
@reboot root sleep 60 ; PATH="$PATH:/usr/sbin:/usr/local/bin/" pihole updateGravity >/var/log/pihole_updateGravity.log || cat /var/log/pihole_updateGravity.log

----

pihole-updatelists.log:
      Pi-hole's Lists Updater by Jack'lul
 https://github.com/jacklul/pihole-updatelists

Opened gravity database: /etc/pihole/gravity.db (23.04 MB)

Fetching ADLISTS from 'https://v.firebog.net/hosts/lists.php?type=tick'... done (29 entries)
Processing... 29 exists

Fetching WHITELIST from 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'... done
Fetching WHITELIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/whitelist.list'... done
Merging multiple lists... done (197 entries)
Processing... 197 exists

Fetching REGEX_BLACKLIST from 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'... done (14 entries)
Processing... 14 exists

Finished successfully in 11.06 seconds.

----

pihole-updateGravity.log:
  [i] Neutrino emissions detected...
^M^[[K  [ ^|^s] Pulling blocklist source list into range

  [i] Preparing new gravity database...^M^[[K  [ ^|^s] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [i] Status: Pending...^M^[[K  [ ^|^s] Status: Retrieval successful
  [i] Analyzed 96293 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
  [i] Status: Pending...^M^[[K  [ ^|^s] Status: Retrieval successful
  [i] Analyzed 41846 domains
  [i] List has been updated
...

----

Health status of this list:	List download was successful (OK)
This list was added to Pi-hole  	5 days ago (2022-01-08 14:44:13)
Database entry was last modified  	5 days ago (2022-01-08 14:44:13)
The list contents were last updated  	8 minutes ago (2022-01-13 17:48:15)
Number of domains on this list:  	41846
Number of invalid domains on this list:  	0
Database ID of this list:	34

**Comment by jacklul** [comment]
Nice, I will push this to master soon.
